### ISSUE TITLE
Add a new zone : Lord Howe Island

### ISSUE THREAD

**Issue by Manu1400** [electricitymaps/electricitymaps-contrib#3286]
### description

Lord Howe Island is a small electricity zone and electricity-independent from Australia 🇦🇺 .

#### geographical
https://en.wikipedia.org/wiki/Lord_Howe_Island

### data

public dashboard: http://photonscada.com/data/perspective/client/LHI => live data via WebSocket

### capacity source
https://www.lhib.nsw.gov.au/infrastructure/renewable-energy

**Comment by wrma6** [comment]
Is this issue something I could work on? Not sure if requirements have changed since the issue was opened or if it is already in progress.

**Comment by VIKTORVAV99** [comment]
Sure! The only requirement that has changed since this was initially opened is that we now require new parsers to use the parser classes documented here: https://github.com/electricitymaps/electricitymaps-contrib/wiki/Building-a-new-parser

Let me know if you need any assistance and I'll see what I can do.

**Comment by wrma6** [comment]
Thanks for the advice! When I get back to this I will try it out.

**Comment by madsnedergaard** [comment]
Closing this for now, if anyone wants to pick it up again feel free to reopen :)
