### ISSUE TITLE
Swedish carbon intensity for nuclear and wind

### ISSUE THREAD

**Issue by jonas9105** [electricitymaps/electricitymaps-contrib#3611]
Hi. I see that you base your nuclear power emissions on an outdated number from an IPCC report. Newer studies show that nuclear in Sweden only emit 2.5g CO2/KWh. Please update your site accordingly to more accurately represent nuclear power.

Source: https://portal.environdec.com/api/api/v1/EPDLibrary/Files/edd6ae95-c679-42c1-98c7-b5818d841c5b/Data

**Comment by jonas9105** [comment]
Addition: Wind power emits 13g CO2/KWh, not 11g. Your website is incredibly inacurate.

**Comment by jarek** [comment]
Thank you for the link! Are you aware of a peer review of this figure?

Just to give an idea of the magnitude of change this would introduce, currently Sweden with 30.09% of electricity being generated in nuclear plants and 9.57% generated by wind turbines has a grid carbon intensity of 46 gCO₂eq/kWh. Using the figures of 2.5 g for nuclear and 13 g for wind would give the grid intensity as approximately 43.3 gCO₂eq/kWh, or about 6.5% lower.

![Sweden electricity emissions calculations](https://user-images.githubusercontent.com/47415/147018004-0093fe8c-3523-4ab3-b989-fd4a1fe0bdd0.png)

This is because most of carbon emissions associated with Swedish electricity production actually comes from the "unknown" category, which is assumed to be "77.22% biomass, 11.2% oil based thermal, 6.33% gas, 4.03% solar, 1.21% peat" based on "the 2019 (2021 edition) eurostat production values": https://ec.europa.eu/eurostat/documents/38154/4956218/Energy-balance-sheets-February-2021-edition.zip/4b1d6665-f303-be7d-a7e5-1e0da16ec0d9?t=1612709565471 per https://github.com/electricityMap/electricitymap-contrib/blob/226bf539d1230210f716fbe97093ed0b05fa9327/config/co2eq_parameters.json#L734-L738

(We have an open issue https://github.com/electricityMap/electricitymap-contrib/issues/1397 to provide a bit more detail for Sweden - split into the grid bidding zones, and breaking out gas and solar - but it looks like biomass, oil, and peat will remain together in "other".)

The other significant source of emissions associated with Swedish electricity production are hydroelectric generation (which uses the IPCC 2014 median 24 gCO₂eq/kWh), then imports from Poland or Lithuania when they happen.

You can see these in the "Carbon emissions" view (timestamps in this screenshot are in UTC-5):

![Sweden electricity carbon emissions view](https://user-images.githubusercontent.com/47415/147017141-37e5a107-d519-44e3-ba26-36e9734c2a53.png)

**Comment by jarek** [comment]
See also previous discussions of the EPD® figure for Swedish Vattenfall nuclear plants:
https://github.com/electricityMap/electricitymap-contrib/issues/738#issuecomment-628496936
https://github.com/electricityMap/electricitymap-contrib/pull/2627

**Comment by VIKTORVAV99** [comment]
Just want to pitch in with my thoughts on the matter since I have been pushing for the nuclear changes for a while now.

@jonas9105: While the 2.5 gCO2eq/kWh number is technically correct it do not account for the full life cycle. I believe the more correct number to use would be 4.1 gCO2eq/kWh as it includes Upstream processes, Core processes and Downstream processes. (Figure 8 on page 27.)

@jarek: I have not found peer reviewed numbers for this data so far.
But the data is certified and do fall in line with the IPCC numbers if you use the total lifecycle emissions of 4.1 gCO2eq/kWh (Min: 3.7 gCO2eq/kWh, Median: 12 gCO2eq/kWh (Current value used), Max: 110 gCO2eq/kWh).
This is also closer to the lifecycle gCO2eq/kw that is reported by UNECE 2020 at 5.1 gCO2eq/kWh for EU28. [Source: table 13 page 74](https://unece.org/sites/default/files/2022-01/LCA_final-FD_0.pdf) (Some real nice data in there that could be useful for #738 too)

I know issue #2627 was closed because you (as a team) where not ready to implement country specific overrides but since #738 has been moving forward rather slowly (at least in public) I am hoping you would reconsider.

**Comment by jonas9105** [comment]
> Just want to pitch in with my thoughts on the matter since I have been pushing for the nuclear changes for a while now.
> 
> @jonas9105: While the 2.5 gCO2eq/kWh number is technically correct it do not account for the full life cycle. I believe the more correct number to use would be 4.1 gCO2eq/kWh as it includes Upstream processes, Core processes and Downstream processes. (Figure 8 on page 27.)
> 
> @jarek: I have not found peer reviewed numbers for this data so far. But the data is certified and do fall in line with the IPCC numbers if you use the total lifecycle emissions of 4.1 gCO2eq/kWh (Min: 3.7 gCO2eq/kWh, Median: 12 gCO2eq/kWh (Current value used), Max: 110 gCO2eq/kWh). This is also closer to the lifecycle gCO2eq/kw that is reported by UNECE 2020 at 5.1 gCO2eq/kWh for EU28. [Source: table 13 page 74](https://unece.org/sites/default/files/2022-01/LCA_final-FD_0.pdf) (Some real nice data in there that could be useful for #738 too)
> 
> I know issue #2627 was closed because you (as a team) where not ready to implement country specific overrides but since #738 has been moving forward rather slowly (at least in public) I am hoping you would reconsider.

Yes, I saw the report from the UN. Averaging 4.1-6.something. However, the 2.5 grams/kWh, do account for full lifecycle costs, it's just only in Sweden. Whereas the UN report is an average of nuclear CO2 emissions in the EU. Anyways, thanks.

**Comment by VIKTORVAV99** [comment]
> Yes, I saw the report from the UN. Averaging 4.1-6.something. However, the 2.5 grams/kWh, do account for full lifecycle costs, it's just only in Sweden. Whereas the UN report is an average of nuclear CO2 emissions in the EU. Anyways, thanks.

The 2.5 gCO2eq/kWh only include Upstream, Core and Core infrastructure emissions but do not account for the Downstream and Downstream infrastructure. So while it's true the reactors themselves only generates 2.5 gCO2eq/kWh the added infrastructure to connect them to the grid, distribution losses, transportation of materials and more brings that number to 4.1 gCO2eq/kWh. As there is no other way to account for these emissions using the current model I believe this is the most accurate number.
Here you can see a full breakdown from Table 7 on page 26:
![image](https://user-images.githubusercontent.com/30777521/158150985-8d6e1250-cf61-4a02-817d-cea61af14b92.png)
_Table 4 on page 19 breaks down the categories as well as Figure 7 on page 21._


The IPCC and UNECE numbers I mentioned is just to show that the data is not far off from the average in the EU and within the IPCC range for nuclear emissions.

**Comment by VIKTORVAV99** [comment]
@jonas9105 now that Electricity Maps have added regional emissions we can start looking into more sources for regional emissions. You mention wind in the title but I don't see a source for it, could you please provide it if it's still relevant?

As for nuclear I have already talked a bit with the team and we are holding off on it a bit for now until we can find a 3rd party study that either reinforce the values that Vattenfall via it's EPD or a new value that can be peer reviewed.

**Comment by madsnedergaard** [comment]
Numbers are updated, closing this
