### ISSUE TITLE
Improve biomass emission factor

### ISSUE THREAD

**Issue by ofenaus** [electricitymaps/electricitymaps-contrib#3727]
### Discussed in https://github.com/electricitymap/electricitymap-contrib/discussions/3721

<div type='discussions-op-text'>

<sup>Originally posted by **ofenaus** January 29, 2022</sup>
According to the quoted source document for emissions ("IPCC 2014") the direct emissions for biomass (dedicated) are not 0. Instead the footnote says they are "significant" - which is correct, actually they are higher than the emissions of coal. If they were 0, the IPCC would have used this value like they did for hydropower or geothermal. But they are not.

Currently electricitymap is using "accounted emissions", not real emissions:

https://www.chathamhouse.org/2017/02/woody-biomass-power-and-heat/2-accounting-biomass-carbon-emissions

I strongly recommend to have a look into the most recent scientific papers on this topic, e.g.

https://www.researchgate.net/publication/357375767_Primeval_natural_and_commercial_forests_in_the_context_of_biodiversity_and_climate_protection_Part_2_The_narrative_of_the_climate_neutrality_of_wood_as_a_resource

Especially the blue box on page 33 outlines the issue of non-existant millions tons of carbon dioxide from woody biomass.

The IPCC itself says that direct(!) emissions from wood are actually amongst the highest amongst all energy sources (page 2.23).

https://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/2_Volume2/V2_2_Ch2_Stationary_Combustion.pdf

More sources:
https://iopscience.iop.org/article/10.1088/1748-9326/aaa512/pdf
https://publications.jrc.ec.europa.eu/repository/handle/JRC122719
https://www.wwf.eu/?2128466%2F500-scientists-tell-EU-to-end-tree-burning-for-energy

The IPCC models you are using did NOT assess use of forest-derived wood pellets for electricity:

https://www.nrdc.org/experts/sasha-stashwick/what-ipcc-really-says-forest-biomass-climate-change

This becomes VERY clear if you have a look at the FAQ published by the NGGIP:

https://www.ipcc-nggip.iges.or.jp/faq/faq.html

Q2-10:

The IPCC guidelines provide the simplifying assumption (Tier 1 method) regarding CO2 emissions and removals associated with annual biomass (e.g., corn, colza) that over the course of a year, the CO2 emissions from the combustion/oxidation/decay of annual biomass are balanced by carbon uptake prior to harvest, within the uncertainties of the estimates, so the net emission is zero.

This assumption is ONLY valid for annual biomass. Woody biomass has never been declared net-zero by the IPCC. Net-zero biomass is only an accounting rule, not a scientific fact:

https://ens.dk/sites/ens.dk/files/Bioenergi/biomasseanalyse_final_ren_eng.pdf

At the moment electricitymap is not providing accurate data and is supporting greenwashing of dirty biomass. Your work is actually contradicting the efforts of pretty much every environmental protection organization:

Fridays For Future:
https://twitter.com/BeyondBurning/status/1470364778631684108
Robin Wood:
https://www.robinwood.de/pressemitteilungen/holz-statt-kohle-klimaschwindel-bei-der-energiewende-nicht-f%c3%b6rdern
WWF:
https://www.wwf.eu/?2128466%2F500-scientists-tell-EU-to-end-tree-burning-for-energy
EEB:
https://eeb.org/wp-content/uploads/2021/09/Where-theres-fire-theres-smoke_domestic-heating-study_2021.pdf
FERN:
https://www.fern.org/fileadmin/uploads/fern/Documents/briefingnote%20bioenergy_German.pdf
Greenpeace:
https://www.greenpeace.org/eu-unit/issues/nature-food/45768/5-reasons-why-burning-trees-for-energy-is-bad-for-climate-people-and-nature/
Somo:
https://www.somo.nl/wood-pellet-damage/
...

To further support this I would like to draw your attention to the ongoing debate on the taxonomy for gas and nuclear energy. If the taxonomy for gas would be ratified:

will you continue use the current emission values for gas or
will you present emissions according to the taxonomy?

And will you only apply this for countries inside the EU?

If you apply the logic you are currently using for woody biomass, countries using significant amounts of gas would instantly have to be reported "green" without any actual change to their energy production.

If this appears like greenwashing to you: that is exactly what is currently done for reporting of emissions from woody biomass.

Please take action and decide, whether you want to monitor "accounted emissions" or actual emissions. And please be transparent towards your users about your decision and the methodology used. </div>

**Comment by jarek** [comment]
Do you know a data source that describes which regions or power plants use woody biomass as opposed to annual biomass?

**Comment by ofenaus** [comment]
Hi @jarek . I am not even sure such a source exists. I am only aware of this report:
https://www.ieabioenergy.com/wp-content/uploads/2021/11/CountriesReport2021_final.pdf
but they do not specify. However page 10 and 11 (solid biomass) are worth a read.

I am absolutely aware of the point you would like to address, as the data source would have to differentiate between the proportion of annual biomass and woody biomass to be used as reliable source for emissions.

Let me do some additional research, if I find something, I will notify you immediately.

**Comment by ofenaus** [comment]
Hi @jarek 

I would like to add this article:

https://www.chathamhouse.org/2021/10/greenhouse-gas-emissions-burning-us-sourced-woody-biomass-eu-and-uk

**Comment by gwpicard** [comment]
Jumping in here — 
@ofenaus I agree with you that our methodology presents obvious limitations. We also draw a strong line when it comes greenwashing, which is one of the key reasons behind why electricityMap exists in the first place—from pushing for the adoption of consumption mix values (to push against some stating that they are running on X% of renewables when only looking at production), to explaining [why green electricity contracts are misleading](https://electricitymap.org/blog/green-electricity-contracts/). 

To build on this point, we definitely also would never label gas as "green". It is easier not to give gas 0 direct emissions because it is much less controversial and more straightforward to describe the emissions intensity of a fuel with a formation period that takes place over tens of millions of years.

Because of the complexity of biomass, we need (as @jarek points out) to find a source that can tell us all three of: 
1. An assessment of woody biomass / forest-derived wood pellets emissions intensity by country
2. the breakdown of their use separating heating from electricity generation
3. within electricity generation, what fraction of reported biomass is annual biomass vs woody biomass.  
Without this information, it is difficult to right off the bat to update and determine these numbers in our data. This is why we added our addendum to the direct emissions intensity figure, knowing that the assumption is "correct" within a very limited scope.

We want to make to make our data better, while also be able to push this debate forward by showing data that we can support with good arguments and data sources. This is also why #738 is a really important issue for us, because biomass remains a bit of a thorny issue until we do this work.

We, as much as you, do not want to let people "off the hook" and make them feel good about numbers that don't represent the physical reality. Much of the work that has been done through electricityMap is specifically to address some of the greenwashing in the space (and we don't currently show direct emissions on the map as well partly for this reason). We try as much as possible to be transparent, which is also why we have an open source community to raise these issues and tackle them as a community, and not hide behind paywalls with no explanation as to how we came up with numbers.

As a final point, I would like to ask you to approach these topics and discussions with empathy and consideration for our work and the hard work of this community. We all want to do the right thing, and we constantly strive to move forward discussions on difficult issues like these. But we do so with respect and understanding, without making assumptions about people's intent without context. Seeing that you opened your first discussion in January (which is great!), it's good to remember that this community has been around for a few years and there is a lot of previous context and deliberation behind many of the decisions taken.

We always welcome new contributions and appreciate bringing to light new ideas and issues. The data sources you shared are great and we will definitely keep a record of them for our work on #738. But while contributions are appreciated, we want to remind you that this is a space for respectful dialogue with consideration for others.

**Comment by ofenaus** [comment]
Hey Guillaume, thanks for the clear words. I really appreciate you being very transparent about the issue you are having with biomass data. This is a _much_ better answer than "we are using IPCC data, so everything is fine and btw. trees regrow". As I obviously dug myself into the topic pretty deeply, I fully understand the challenge you are having with getting your hands on reliable data (or any data at all) regarding annual/woody biomass per country etc. etc.

I would like to draw your attention to one issue: people are using your data on social media etc. to make a point about a specific country or method of energy generation. If countries are burning woody biomass on a massive scale, these countries will appear very green, very clean, very much on a right track towards climate neutrality, although they emit more CO2 than burning coal - supported by screenshots and data from electricitymap. I strongly advise to find a solution for this issue, because - even you are opposing any form of greenwashing - your data will be used to do exactly the same or even abused by lobbyists.

**Comment by madsnedergaard** [comment]
Similar to #4777, closing this to keep discussions on one place (with a link back to this) :)
