### ISSUE TITLE
Data for British Columbia (Canada)

### ISSUE THREAD

**Issue by gwpicard** [electricitymaps/electricitymaps-contrib#3801]
There seems to be some data for BC Hydro balancing authority. It is delayed by a couple days, but I thought it relevant to tag here as we start to move toward more estimation models for real time data.

https://www.bchydro.com/energy-in-bc/operations/transmission/transmission-system/balancing-authority-load-data.html#

**Comment by jarek** [comment]
For a bit more data, BC generation is about 90-95% hydro, see https://github.com/electricitymap/electricitymap-contrib/issues/3575#issuecomment-982221906

**Comment by jarek** [comment]
The exchanges are already implemented in https://github.com/electricitymap/electricitymap-contrib/blob/master/parsers/CA_BC.py

**Comment by gwpicard** [comment]
But could we also build the real-time production parser?

**Comment by jarek** [comment]
The page you linked has exchange data. Do you see real-time production data available anywhere?

I see https://www.bchydro.com/energy-in-bc/operations/transmission/transmission-system/balancing-authority-load-data.html with "Balancing Authority Load Data" claiming to be "Current Hourly" but the text says it'll be at best a day delayed ("Each day provides information for the previous day (Monday updates provide information for previous Friday, Saturday and Sunday)." and the provided files as of right now only have data up to April 12th

**Comment by q--** [comment]
When I checked it, it went up to April 30, so more than half a month ago. Still could be used to build a parser; a consumption parser should definitely be doable, production... maybe, since we have exchange data to the US and Alberta, and I don't have the impression there is an exchange with Northwest Territories or Yukon as it's not on the exchange [actual flow data](https://www.bchydro.com/energy-in-bc/operations/transmission/transmission-system/actual-flow-data.html) page mentioned before.

It appears that the exchange data only goes back 7 days though, so combining that could be hard unless there's some way to query either that site or ElectricityMap for historical exchange data to do the math.

**Comment by jarek** [comment]
Right now it's June 27th, but the "Current Hourly" only has data up to May 31st. It could perhaps be used to guesstimate the demand.

Electricity Maps team, please let us know when you'd be interested in building an estimate for British Columbia then we can parse the XLS.

**Comment by jarek** [comment]
Ah, actually the parser currently has a `fetch_consumption()` function implemented and the file it fetches also has data up to May 31st, so there doesn't appear to be anything new to add right now.
