### ISSUE TITLE
[RFC] Re-arranging production modes in the breakdown table

### ISSUE THREAD

**Issue by madsnedergaard** [electricitymaps/electricitymaps-contrib#4109]
## Description

We're thinking about re-arranging the way production modes are shown on the app:

<img width="434" alt="Screenshot 2022-05-09 at 15 08 19" src="https://user-images.githubusercontent.com/3296643/167416828-1dd7e88d-7aa4-4ecd-b96b-e33d0b539d8c.png">

### But we need your feedback 🤔 

We've identified the following approaches to sorting the breakdown - we'd love to hear your feedback on what **you** think makes most sense!

**Please try it out on the links below and vote by reacting with the emoji for your favourite approach:**

👍  [By alphabet](https://staging.electricitymap.org/zone/DE?sortingmode=alphabetical)
 🎉  [By current production](https://staging.electricitymap.org/zone/DE?sortingmode=production)
❤️  [By capacity](https://staging.electricitymap.org/zone/DE?sortingmode=capacity)
🚀 [By emission factor](https://staging.electricitymap.org/zone/DE?sortingmode=emissionFactor)

(Also feel free to comment with your thoughts and inputs on this!)

**Comment by jarek** [comment]
I would expect the table order to match the chart order. Are you also thinking of changing the chart order?

**Comment by pierresegonne** [comment]
+ 1 on matching order with order on the timeseries chart

**Comment by madsnedergaard** [comment]
Thanks for the comments! The order is currently based on baseload and "dispatchability" - this makes sense for the graph, but not necessarily for the breakdown-table, and especially not for non-energy-expert :D

What is the reason for having the order on the chart and breakdown match - do you look at both on the same time, or use the table for reference of the names?
I'd like to understand the use case to figure out if we can solve that in a better way (for example with legends on the graph) :)

**Comment by VIKTORVAV99** [comment]
Hmm I think I would want them ordered by co2eq factor with unknown always last in the table.
But I would prefer "baseload" in the graph so we have as many "straight" lines as possible (makes it easier to read).

By current production is a interesting idea but I am worried it might cause the bars to "jump" around when using the time slider and the production changes and cause similar problems as in #3807 if the table potentially has to re-render on every data point.

**Comment by jarek** [comment]
Hm so checking again now, it looks like currently the Electricity Map table order is the reverse of chart order. Table has baseload-type sources first, and chart has baseload-type sources at the bottom.

> What is the reason for having the order on the chart and breakdown match - do you look at both on the same time, or use the table for reference of the names?

Hm... I think it's mostly because I don't see why it _shouldn't_ match. (Or be same order but reversed, as now.) It's the same data, so why would it not have the same order? I don't look at both at the same time, and I don't need the reference for the colours, but then I've been looking at these charts for years so I know what's what.

Thoughts on the options you suggested:

- By alphabet: this seems fine, and matches the exchanges which are listed in alphabetical order below. My only suggestion would be to separate out the battery/storage options because it feels strange to have them apart
- By current production: seems fine. I think there's a bug because gas is too low for its production right now, but otherwise mostly fine. It feels a little weird due to sorting by generation but the table also showing capacity, so the ends of the capacity bars aren't in order, but it would also feel weird to sort by capacity. I actually kind of like the lines moving around when using the time slider as production changes over time.
- By capacity: doesn't really make sense to me since meaning of capacity is different for baseload vs peaker vs non-dispatchable sources
- By emission factor: the sample link https://staging.electricitymap.org/zone/DE?sortingmode=emissionFactor showed the order "coal, biomass, solar, geothermal, hydro, nuclear, wind, hydro storage, unknown, oil, gas, battery storage" which I don't think is right, so it's tough to evaluate. Switching to France showed highest emissions first in the table (coal, unknown, oil) - if anything I would suggest lowest emissions first. But I would guess that either order might not be particularly informative to have a very-high-capex baseload source like nuclear next to low-capex non-dispatchable wind.

I like OpenNEM's chart order, and also the similar Fraunhofer chart order https://energy-charts.info/charts/power/chart.htm?l=en&c=DE : baseload at bottom, non-dispatchables at top. I actually also like Electricity Map chart's placement of peaker sources (gas, hydro, battery) above non-dispatchables which I feel highlights the peakers' value in filling in the gaps. In the end, I would suggest having the table order match or reverse the chart order, or maaaaybe one of the first two options suggested.

**Comment by VIKTORVAV99** [comment]
Just a crazy idea here but do we have to pick?
We could introduce all or some these options as options the users themselves could pick and then keep the current order as the default (maybe with a modification or two if needed)?

A dropdown menu would be a relatively simple thing to add.

**Comment by mathilde-daugy** [comment]
Hey everyone, I'm reviving this issue. Would it make sense to order by carbon intensity ? This would maybe help emphasize renewable production (an idea @tonypls and i had)

**Comment by madsnedergaard** [comment]
> Hey everyone, I'm reviving this issue. Would it make sense to order by carbon intensity ? This would maybe help emphasize renewable production (an idea @tonypls and i had)

That's actually the "by emission factor" approach discussed in above comments :) 

And since we now have regional emission factors, this would mean the order could switch around depending on which zone is selected. I think this would make comparison of values harder, but maybe still worth a protoype? :)

**Comment by mathilde-daugy** [comment]
maybe we could just use the default emission factors published by IPCC so it's the same for all zones and there is some logic to it?

**Comment by VIKTORVAV99** [comment]
Using the default values would solve the positional issues but then it wouldn't really follow a "logical" ordering by looking at one zone.

I think we need to rethink this and maybe cherry pick (some of the) ordering like we have done today.

**Comment by madsnedergaard** [comment]
Closing this again, thanks for all the inputs - we're doing some larger changes, so this will be revisited later :)
