### ISSUE TITLE
Tooltip of production history shows mt instead of kg for unit of emissions

### ISSUE THREAD

**Issue by torokati44** [electricitymaps/electricitymaps-contrib#4317]
See this screenshot:
![image](https://user-images.githubusercontent.com/288816/176998187-c47152e5-29ac-4d43-990b-f1f464776862.png)

Similar to #793.

**Comment by jarek** [comment]
Removed the "translations" label because the units don't seem to be in the translations, they're only in the code.

Maybe the code prints "mt" and means "millitonnes" :flushed: 1 millitonne is of course 1 kg...

It might be because https://github.com/electricitymap/electricitymap-contrib/blob/master/web/src/components/tooltips/countrypanelexchangetooltip.jsx and https://github.com/electricitymap/electricitymap-contrib/blob/master/web/src/components/tooltips/countrypanelproductiontooltip.jsx use `formatCo2` from `web/src/helpers/formatting` (which converts tonnes to grams when it's less than 1 tonne), but https://github.com/electricitymap/electricitymap-contrib/blob/master/web/src/components/tooltips/countrypanelemissionstooltip.jsx does not?

Actually, I'm not a frontend person at all, but as far as I can tell, this seems to be printed by:

https://github.com/electricitymap/electricitymap-contrib/blob/78f5edbf6fccb30b5e40a7e0d46a04485f250026/web/src/components/tooltips/countrypanelproductiontooltip.jsx#L91

which does use formatCo2... so I dunno what's the cause ultimately.
