### ISSUE TITLE
Mobile app installs old version on fresh install [Android]

### ISSUE THREAD

**Issue by waltonzt** [electricitymaps/electricitymaps-contrib#4442]
**Describe the bug**
When downloading the android app for the first time it appears as if an older version of the app is first installed.

Closing and reopening the app does not seem to resolve the issue but after a little while the new version loads when the app is opened.

**To Reproduce**
1. Download app from Play Store
2. Open app
3. See old app

**Expected behavior**
The new app to load upon install

**Screenshots**
<video src='https://user-images.githubusercontent.com/17326871/184026721-7714a8b1-da13-4fea-9c58-1716536396cc.mp4'/>

**Desktop (if relevant):**
 - OS: Android

**Smartphone (if relevant):**
 - Device: Samsung S21
 - OS: Android 12

**Additional context**
I also notices that the app icon uses the old logo on android.

**Comment by Kongkille** [comment]
@tonypls have you ever experienced something like this?

**Comment by corradio** [comment]
I believe this is due to the fact that we have two release tracks: the app store and the code-push release.
When downloading the app, one doesn't get the latest version of the code-push'ed code (one only gets the version that was pushed alongside the app store).
As far as I know this is quite normal and there's not much we can do aside from releasing to app store once a while.

**Comment by Kongkille** [comment]
Yes, I also think the difference will be smaller now that we're going to get code-push working again :)
