### ISSUE TITLE
[feature in development] Regional Emission Factors 🗺️ 🔨

### ISSUE THREAD

**Issue by madsnedergaard** [electricitymaps/electricitymaps-contrib#4737]
<div align="center">
	<img width="589" alt="Regional emission factors" src="https://user-images.githubusercontent.com/3296643/199442712-4ea9d2c6-26bd-43ad-b199-91f02277889c.png">
</div>

### Description
**tl;dr: We're currently implementing regional emission factors!**

Since the dawn of Electricity Maps (or very close to it at least), we have had one grand issue that kept reappearing. It has taken a while, but now we finally have the infrastructure and team in place to work on the this issue: [#738 Refine GHG emission factors by regions](https://github.com/electricitymaps/electricitymaps-contrib/issues/738) 🌍 

Today we mostly use emission factors ([wiki page documenting usage](https://github.com/electricitymaps/electricitymaps-contrib/wiki/Default-emission-factors)) established by the IPCC in 2014, which is not ideal because they are both outdated and do not convey regional differences for the same production modes. With this new feature in place, we will be able to use regional data from reliable sources to give a more accurate estimate for the CO2 impact of different production modes.

All calculations and sources for these regional emission factors will be open and transparent - we'll very soon implement the first few in this repository, so stay tuned! 🔜 

### Timeline

- Right now, the team is working behind the scenes on making this possible - we're aiming to have a first version out before end of November 2022
- At first we will focus on US and a few EU zones - but we're building an open, scalable system that means everyone can contribute with new data for new zones!
- Once it's launched and working, we will document how to contribute and work on making it as easy as possible to gather data, update regions and build the best possible map together with you 💚 

**We will share updates on this issue whenever there's anything new.**

_Lastly, we decided to keep conversations about this topic in a new issue here instead of continuing in #738, as the conversations there were focused on specific data sources, while we here want to talk about the functionality itself_

**Comment by VIKTORVAV99** [comment]
I don't know what the current target is in regards to production modes but I think we should aim to keep onshore and offshore wind separate, biomass and waste separate, etc (this goes for all aggregated production modes). This is in order to allow us to dynamically compose hourly co2intensities based on the underlying regional data for each mode we currently group.

Just a small example with made up data:
```
Current model:
Wind: 100MWh at 12gco2eq
Resulting co2eq intensity:
12gco2eq

New dynamic model:
Onshore wind: 50MWh at 12gco2eq
Offshore wind: 50MWh at 14gco2eq
Resulting co2eq intensity:
(12 × ("onshore wind"/("onshore wind" + "offshore wind"))) + (14 × ("offshore wind"/("onshore wind" + "offshore wind"))) =
(12 × (50/(50 + 50)) + (14 × (50/(50 + 50)) =
13 co2eq
```

This would allow us to display even more accurate numbers for zones where the parsers split the modes up (ENTSO-E for example) while still showing the grouped production modes we have now and not cluttering up the UI.

I realize this would be another feature in itself but it can't be built if we don't keep this in mind when generating the regional co2 intensities.

**Comment by pierresegonne** [comment]
> I don't know what the current target is in regards to production modes

We're not yet changing the taxonomy for production types :)

**Comment by pierresegonne** [comment]
For reference, the documentation for the regional emission factors is now available on our [wiki](https://github.com/electricitymaps/electricitymaps-contrib/wiki/Emission-factors) 🍾
