### ISSUE TITLE
[Data Issue]:  Production vs Consumption intensity is suspicious

### ISSUE THREAD

**Issue by pierresegonne** [electricitymaps/electricitymaps-contrib#4776]
### When did this happen?

2022-11-16

### What zones are affected?

ex: `DE`

### What is the problem?

carbon intensity for production is much lower than for consumption even though `DE` is almost not exporting.

**Comment by Tachy** [comment]
![2FCB53DC-22DD-4353-8DC2-B316F84625CE](https://user-images.githubusercontent.com/2771003/202908116-0572fa15-3d26-44ca-bfd4-d17e747dddc3.jpeg)
![12D1B02D-B5BC-42AB-9249-073B3949DE9C](https://user-images.githubusercontent.com/2771003/202908117-ba1496d2-939b-4ffa-ae85-16161479679c.jpeg)

**Comment by alyabolowich** [comment]
I think you are using the old emission factors for production and the new ones for consumption. Here's the recalculation of Germany's carbon intensity for 20 Nov 2022 at 15h00.


![image](https://user-images.githubusercontent.com/54064746/202913311-83d13aec-1b25-4f8f-a22f-638cdccee330.png)

The correct number should be 716 but 505 is shown. 

![image](https://user-images.githubusercontent.com/54064746/202913369-087c7666-3a2b-4fba-9979-c237bf5c2ae4.png)

**Comment by corradio** [comment]
cc @unitrium @mathilde-daugy @FelixDQ

**Comment by unitrium** [comment]
I will have a look today

**Comment by FelixDQ** [comment]
Thanks for reporting everyone. We have identified the issue and will have a fix going out later today :-)

**Comment by unitrium** [comment]
Rather credit to @FelixDQ  who found out what was going on.

**Comment by unitrium** [comment]
For transparency here's a small report on what happened on our side


## What happened:

On 20/11/2022, we started getting reports from our community on suspicious data for a certain number of zones. The reason being that the carbon intensity of certain zones was much higher for consumed electricity than the actual produced electricity even when taking into account imports and exports. This didn’t make physical sense and was quickly pointed out by our quick to notice community.


## How did it happened:

A silent failure in our deployment pipeline meant that some files for the regional emission factors were not deployed and therefore replaced by our fallback values. This caused a drift between how production and consumption carbon intensity were calculated.

## When did it happen:
The data drift started after the roll out of the regional emission factors on the 16th of November.

## What is the extent of the problem:

All zones with regional emissions factors were affected by this issue. However, only data processed after the 16th of November, when regional emission factors were enabled, were affected. All previous data was still valid as we didn’t run the regional emission factors on our entire dataset at the moment.

## How did we remediate it:

We fixed the deployment issue and rolled out a new flowtracting container which would take into account the latest changes. Afterwards we ran the flow tracing on our entire dataset to fix all the miss computed data from the 16th of November and also apply the regional emission factors to our historical data.

## Which steps are we taking to prevent it from happening again:

The amazing surveillance work our community is doing will be added to our automated alert system. This physical rule that carbon intensity for consumption and production will be integrated so that we would notice this kind of stuff faster. Furthermore, we’re discussing adding an extra step in our processing pipeline to better flag suspicious data.
Again we want to emphasize the high standard of expectations our community holds us to and thank you for the all your help.
