### ISSUE TITLE
GP parser works locally but fails when run in the backend?

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymaps/electricitymaps-contrib#4828]
## Description
#4742 introduced a new parser that should have enabled Guadalupe (GP) to be colored on the map but this is not the current case.

Currently the parser returns a non standard format that includes a `estimated: <bool>` in the return object to flag if the data is estimated or not since the API endpoint for the parser includes both and without the estimated data the lag would be months.

Now this works locally without any issues but it seems to fail when ran in the backend probably due to the extra key in the return object.

Parser logs:
```log
Expecting value: line 2 column 1 (char 1)
File "/projects/feeder-electricity/src/lib/fetch_data.py", line 172, in launch_parsers
    objs = res.get(timeout) or []
File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 771, in get
     raise self._value
File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 125, in worker
     result = (True, func(*args, **kwds))
File "/projects/feeder-electricity/src/lib/fetch_data.py", line 164, in <lambda>
     lambda: parser(    File "/contrib/parsers/FR_O.py", line 166, in fetch_production     production_objects, date_string = fetch_data(
File "/contrib/parsers/FR_O.py", line 137, in fetch_data
     data = response.json()
File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
     return complexjson.loads(self. Text, **kwargs)
File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
     return _default_decoder.decode(s)
File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
     raise JSONDecodeError("Expecting value", s, err. Value) from None
```

Now I see two solutions to this:

1. Ignore the estimated data and return a normal parser production object and accepting the months long delays.
2. Modify the backend to accept the new object form and either reject the estimated data or use it in place of Electricity Maps own estimation models. In theory the estimations from the TSO should be higher fidelity as they have access to more data points.

>**Note**
>This applies for all zones using the `FR_O.py` parser.

**Comment by VIKTORVAV99** [comment]
@pierresegonne we talked a little about this already a while back when I re-did the FR_O parser so pinging you in here as well.

**Comment by pierresegonne** [comment]
Hey, sorry for the delay here, 

I think the best here would be to update our schema for parser events to include a field that describes the event (measured vs estimated). 

This requires touching some key infra elements so I'm not going to do it now huhu

I'll try it out in January when we have some slack. 

Otherwise, the only ways we could include it right now are:

1. ignore the estimated field and consider that because it comes from the TSO, it's "measured" 
2. Only fetch the consolidated data

I think 1. is preferable. Most of our data follows the same lifecyle where the data we get real time is not really measured and will be consolidated later on. 

So what I would encourage you to do is to remove the estimated field in the return object and put a note in the parser to make it clear.

**Comment by VIKTORVAV99** [comment]
I'll comment out estimated field in the return object and add a description to it. Then I will modify the parser as needed in January when we have worked out the details. 👍🏻

**Comment by VIKTORVAV99** [comment]
Closing this as the estimated flags have been added in the new parser classes.
