### ISSUE TITLE
UK Data Accuracy?

### ISSUE THREAD

**Issue by mfro0** [electricitymaps/electricitymaps-contrib#4849]
I know the map says "estimated", but notice there is a huge discrepancy between what Electricity Maps shows and this UK energy monitor:

http://www.gridwatch.templar.co.uk/

Can you say where the discrepancy stems from and which one is more accurate?
Thanks.

**Comment by VIKTORVAV99** [comment]
There is currently no data available for UK or specifically GB in the ENTSO-E transparency platform which we used to fetch the data. This means since we can't get any source data the estimation models took over and the further away from any real data the less accurate they will get. There is a support ticket opened on the matter and you can track it better in here #4835.

**Comment by VIKTORVAV99** [comment]
That should be fine but with the merger of #4881 I'm hoping we can close all of these. 🙂

**Comment by unitrium** [comment]
Closing this issue in favor of #4835 to track remain tasks there.
