### ISSUE TITLE
Up to date wind and solar generation capacities in Finland (FI)

### ISSUE THREAD

**Issue by msaynevirta** [electricitymaps/electricitymaps-contrib#4857]
Fingrid, the national grid operator of Finland, provides two APIs for more up to date estimates for Finnish wind and solar generation capacities. New renewable generation capacity has been growing quite quickly in the recent years with wind generation capacity already up 1917 MW since January this year.

Based on #4571 it seems that parsing capacities is not currently supported, but it could be good to at least update the figures every now and then based on the more up to date dataset.

Sources: [wind capacity](https://data.fingrid.fi/en/dataset/total-wind-production-capacity), [solar capacity](https://data.fingrid.fi/en/dataset/total-solar-production-capacity)

**Comment by VIKTORVAV99** [comment]
> Based on #4571 it seems that parsing capacities is not currently supported, but it could be good to at least update the figures every now and then based on the more up to date dataset.

That's not exactly true but it's not wrong either. We can return the capacity as a part of the production parser but since this would need a different parser it's probably out of the question until we can run these parser independently.

However you can manually update the `config/zones/FI.yaml` file with the new capacities if you'd like. 🙂
