### ISSUE TITLE
New color scale is not a perfect ramp

### ISSUE THREAD

**Issue by phiphou** [electricitymaps/electricitymaps-contrib#4858]
In the new color ramp, the same color is applied between 860 and 1000g (#381d02).

**Comment by VIKTORVAV99** [comment]
> In the new color ramp, the same color is applied between 860 and 1000g (#381d02).

Is this on the app by any chance?
This was recently updated but I don't think it's included in the mobile builds yet.

**Comment by phiphou** [comment]
I checked the ramp on the website with Photoshop (difference is not too visible)... Not sure for the app...

**Comment by VIKTORVAV99** [comment]
> I checked the ramp on the website with Photoshop (difference is not too visible)... Not sure for the app...

The minimal difference in the upper range is intentional. Since there if just a few zones that can even go to 1500 co2eq/kWh and most max out at 1100 co2eq/kWh.

This is so the colors more or less match our past color range when in the 0 to 1100 range so it's easier to compare screenshots and the alike from the past (before the co2eq emission updates).

**Comment by phiphou** [comment]
That's ok, fine ;)

**Comment by VIKTORVAV99** [comment]
Closing this as the current functionality on the web is intentional and it will be deployed on mobile soon.
