### ISSUE TITLE
Country aggregation incomplete/inconsistent

### ISSUE THREAD

**Issue by PaulCornelissen** [electricitymaps/electricitymaps-contrib#4951]
## Some Islands are not aggregated in country mode
E.g. Orkney is not aggregated with the rest of UK.
Corsica is not aggregated with France.
The Balearics and Canaries are not aggregated with Spain.
Åland is not aggregated with Sweden.

Or is it not meant to aggregate Islands? Then why are Sicily, Corsica aggregated with Italy and Denmark East with Denmark West? 

Or is it only meant for interconnected Islands? Then the Balearics should be added to Spain, but Bornholm should be removed from the Denmark aggregation and the channel islands from Australia.

Currently it seems rather arbitrary.

**Comment by VIKTORVAV99** [comment]
Okay there a few different reasons for why the zones you mentioned has not been aggregated so I'll break them down one by one.

Orkney is not aggregated with the rest of the UK because we are missing data for some UK zones and we don't want to aggregate zones unless we have all the data. We recently added a new source for GB-NIR though so when we are done with that we can look into aggregation of the UK again (but we are still missing the Shetland islands).

Corsica will be aggregated with France once https://github.com/electricitymaps/electricitymaps-contrib/pull/4853 is merged so to avoid making 2 breaking changes to our data.

The Spanish islands are not aggregated with Spain due to https://github.com/electricitymaps/electricitymaps-contrib/issues/4733 and hopefully we can come up with a solution to that soon once the rewrite is done and we have a little more time on our hands.

Åland is not aggregated with Sweden because it's an autonomous region of Finland. We have decided that autonomous regions that have their own ISO county codes should stay independent, at least for now.

The long term plan is to aggregate all countrys that have multiple subzones (with the exception of autonomous regions that have their own ISO country codes).
