### ISSUE TITLE
map projection

### ISSUE THREAD

**Issue by Antoine1408** [electricitymaps/electricitymaps-contrib#5109]
Hello, your map is not linear and increases the proportion towards the poles. 
I think in reality the size of the countries closer to the equator would be larger.
I think in reality the size of the countries closer to the poles would be smaller.
So the island "Greenland" appears very large and the countries at the equator are too small.
Please use another view of the map which would be more precise to the actual size of the real surface.
And finally put the equator-line to the the center of the vertical picture = 50% distance from each edge (up/top/north and down/bottom/south).

Otherwise I like very much this presentation and I wish you all the best.
Kind regards, Antoine Hauska, Austria

**Comment by tonypls** [comment]
Hi Antoine, thanks for bringing this up.

We use a Mercator projection for our map similar to Google Maps and most major map providers. You can read more about it [here](https://en.wikipedia.org/wiki/Mercator_projection). 

I think the distortion may be more pronounced because we allow more zooming out than most maps. As this is the most common projection across the web and users are familiar with it, I'm going to close this issue. Thank you for your feedback and we will take this into account for further discussions around the map projection used.

[Here](https://www.thetruesize.com/#?borders=1~!MTYyNTk4NDg.MzU4MjA2NQ*MzIxOTMzMzA(NTI5ODc5OQ~!CONTIGUOUS_US*MTAwMjQwNzU.MjUwMjM1MTc(MTc1)MQ~!IN*NTI2NDA1MQ.Nzg2MzQyMQ)Mg~!CN*OTkyMTY5Nw.NzMxNDcwNQ(MjI1)MA) is a nice tool to check the real size of a country and see how distorted most maps are.

**Comment by Antoine1408** [comment]
Thank you Tony for the informative answer.
All the best, Antoine Hauska
Peterhofgasse 8/14
2500 Baden / Wien
+43 (0) 68 11 0330 299
________________________________
Von: Tony ***@***.***>
Gesendet: Montag, 20. Februar 2023 14:02:06
An: electricitymaps/electricitymaps-contrib
Cc: A. Hauska; Author
Betreff: Re: [electricitymaps/electricitymaps-contrib] map projection (Issue #5109)


Closed #5109<https://github.com/electricitymaps/electricitymaps-contrib/issues/5109> as completed.
