### ISSUE TITLE
how about incorporating pricing

### ISSUE THREAD

**Issue by firsttest12** [electricitymaps/electricitymaps-contrib#5200]
Real time pricing info is available on a nation state basis....

http://cena-pradu.pl/electricity-price.html

This is a relevant part of - and driver in - the debate. How about starting to incorporate it in the app?

**Comment by VIKTORVAV99** [comment]
Hi @firsttest12!

We are already parsing price data for most of Europe, and we previously showed it in the app but due to licensing issues we were not allowed to redistribute (show) this data anymore unfortunately. Potential solutions are already discussed in #5128 so I'm going to close this issue but feel free to add any additional information to that issue.
