### ISSUE TITLE
Capacity PT<->ES

### ISSUE THREAD

**Issue by brandongalbraith** [electricitymaps/electricitymaps-contrib#5411]
## Description

While casually reviewing Portugal's real time generation mix, I noticed that the PT<->ES interconnector was exceeding what ElectricityMap has as max capacity:

![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/350893/a490750e-dcba-4d76-9fbc-52f02ca341aa)

With a quick Google search, I found [Analysis of Portugal-Spain interconnection capacity and monitoring
of compliance with the minimum level of margin available for
cross-zonal trade in 2020](https://web.archive.org/web/20230516184334/https://www.erse.pt/media/kevnjc3r/portugal-spain-interconnection-analysis-and-maczt-monitoring-report-english-version-2020.pdf).

![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/350893/677199f1-13c8-414d-9420-63df961d4a25)

![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/350893/cc7096d7-20de-429e-82da-553485466961)

I propose adjusting the interconnector limits in ElectricityMap as follows:

Spain->Portugal: 5085MW
Portugal->Spain: 4545MW

If the ElectricityMap is amiable to this change, I'll submit the appropriate PR. Thank you!

**Comment by VIKTORVAV99** [comment]
I see no problem with adding these new capacity figures, just remember to update the DATA_SOURCES.md file.

**Comment by RGarrido03** [comment]
@brandongalbraith Thank you very much for finding this. I'm the person who added the previous Portugal⇄Spain capacities, and I must congratulate you, since I spent a lot of minutes searching for those values and I wasn't able to reach a so-well-explained PDF like this one 😆

However, I think that your PR (#5412) has an issue: the import and export values are swapped. In Portugal, the app reports the import capacity from Spain is 4.55GW, when it's actually 5.09GW (and vice-versa). Can you please submit another PR? If you want, I can do it as well, but I don't wanna do that without your permission :)
