### ISSUE TITLE
Germany data quality

### ISSUE THREAD

**Issue by mueslo** [electricitymaps/electricitymaps-contrib#5422]
## Description

German data quality is currently very bad. As far as I can tell, it's because for the past week or so, for example, ENTSO-E has only been reporting a few types of generation units for Germany (Geothermal, Offshore Wind and Lignite).

Electricitymaps is showing some estimate that is extremely wrong and misleading (way too  much pumped storage generation, wind often far too low). It is probably better to grey out Germany like other countries for which data is not available until better data is available.

**Comment by VIKTORVAV99** [comment]
I don't think we are going to disable the estimations for Germany as there are both internal and external services that rely on that data being available, even if degraded due to the lack of source data from ENTSO-E. 

However we are working on improving the estimation models, especially for solar and wind. I'll check with the team on Monday and see what they say about the issue. I'll also reach out to ENTSO-E on Monday and see what they say.

I would also like to note that once the data is available again we will re-fetch it and correct our data.

**Comment by w-flo** [comment]
TransnetBW currently reports N/A for every type of generation they would usually report on. It seems like the other three transmission system operators report correct data (hence lignite, offshore wind and geothermal are unaffected, as these types of generation do not exist in Baden-Württemberg). Maybe electricitymaps could use the available data from other transmission system operators, and only estimate the TransnetBW numbers that are missing. Or maybe if it's impossible to implement quickly, I guess TransnetBW would hopefully fix their Entso-E reporting soon.
