### ISSUE TITLE
No data for Germany -> grayed out on map

### ISSUE THREAD

**Issue by w-flo** [electricitymaps/electricitymaps-contrib#5485]
## Description
I believe this is a backend issue.

Since yesterday, Germany is grayed out on the map and no data is available.

For example, the backend response for `https://app-backend.electricitymap.org/v6/details/yearly/DE` is, according to firefox developer tools:
```
{
	"data": {
		"hasData": false,
		"stateAggregation": "yearly",
		"zoneStates": {}
	}
}
```

**Comment by VIKTORVAV99** [comment]
This is unfortunately deliberate as we weren't getting any data from ENTSO-E for over 24 hours and estimation models started to behave strange.

So instead of showing wrong data we decided to disable it until we get data from ENTSO-E again.

**Comment by w-flo** [comment]
Oh, that makes sense. TenneT is showing "N/A" for all production types at Entso-E. They have acknowledged the issue:

> We would like to inform you about possible missing data submissions for RO, DE(TenneT), SE, LT & HU observed after the TP maintenance on 18/06/2023.

And they scheduled maintenance for tomorrow, maybe they will try to fix it then.

For situations like this, a "no _current_ data available" mode would be great, so we could still check aggregated data for past years etc.

Thanks again for the explanation. I hadn't noticed these Entso-E problems. Feel free to close this issue, or maybe it should stay open until the data is available again.

**Comment by VIKTORVAV99** [comment]
> For situations like this, a "no current data available" mode would be great, so we could still check aggregated data for past years etc.

Agreed and it is something we have talked about, but we did not have time to shape and implement it in the time required for this event.

Hopefully it will be in place if this ever happens again (let's hope it don't 😅).

I'll leave the issue open until Germany is back on the map.

**Comment by ReneMacon** [comment]
Yesterday morning German electricity production mix caused  556 CO2 g/kWh emmissions, while France had 42 CO2 g/kWh. I posted this as a reader comment at the German newspaper "WeLT" ( https://www.welt.de/vermischtes/article245938660/Robert-Habeck-Ich-bin-auch-nicht-zufrieden-mit-der-Bundesregierung.html#/comment/250389133) with a hint to "electricitymaps.com"  and argued that German heat pumps need a coefficient of performance (COP) 3,5 to cause less CO2 emmissions than a standard gas boiler (160 CO2 g/kWh). The German Green party and its minister of economics, Robert Harbeck, nevertheless prefers heat pumps.

My post was shared by many other readers. Shortly afterwards the German CO2 g/kWh data on electricitymaps.com disappeared. I think it is possible that the "Green" ministry of economics is causing this problem, since your data compromise current German energy policy.

**Comment by w-flo** [comment]
Please keep your conspiracy theories in the Axel Springer comment sections.

Also, you should do some research on the actual emissions of standard gas boilers.

**Comment by ReneMacon** [comment]
Thank's for confirming my hypothesis!

**Comment by VIKTORVAV99** [comment]
Let's keep the discussion on topic guys, this is not the place for discussing this.

**Comment by jsuelwald** [comment]
> Let's keep the discussion on topic guys, this is not the place for discussing this.

Then just moderate (as in delete) these comments?

**Comment by hallyday2023** [comment]
I also assume political reasons that Germany is now a white spot. 
Another reason might also be this article from bild.de:
https://www.bild.de/politik/inland/politik-inland/so-schmutzig-ist-unser-strom-wirklich-dreckschleuder-deutschland-84373434.bild.html
When can the problem be resolved? First whe is again enough power from wind energy.

**Comment by madsnedergaard** [comment]
ENTSO-E finally has data for all TSOs and the bidding zone again! 🤩 
<img width="820" alt="Screenshot 2023-06-21 at 13 41 02" src="https://github.com/electricitymaps/electricitymaps-contrib/assets/3296643/314f65a0-450e-4de2-82af-fbab17f56f85">

We'll enable the zone on the map again ASAP!

**Comment by w-flo** [comment]
Huh, it still shows N/A for me for the DE-LU bidding zone. But TenneT now has valid data for today from 05:30 to 12:30 for me, so that's a start! Country-level data has started appearing a few seconds ago, but is still incomplete. So I guess they're still in the process of actively fixing it.

Also, the planned maintenance should start very soon. They also posted this message today:
> We have further update, missing data should be published for all areas except for  DE(TenneT) [for the time period] after the TP maintenance on 18/06/2023.
> Our IT team and Data provider are working on the issue.

**Comment by madsnedergaard** [comment]
> Huh, it still shows N/A for me for the DE-LU bidding zone

Oh you're right, I was looking at yesterday! 🤦 
But at least they have started backfilling then, so hopefully we'll have recent data soon 😅

**Comment by VIKTORVAV99** [comment]
They had "live" production for about 7 hours today bot now it's all N/A again so we will have to push this.

And for the meaning of soon and ASAP, soon meant when everything is working again, we have no control over this.

ASAP literally means as soon as possible and we'll we can't do anything before that because the data source is down.

**Comment by ReneMacon** [comment]
The German members of ENTSO-E are TransnetBW GmbH, TenneT TSO GmbH, Amprion GmbH, 50Hertz Transmission GmbH. Their economic well-being completely depends on the decisions of the German Federal Network Agency. 
The current head of this Agency is the former Green Party Minister Klaus Müller. 

The data you publish on electricity maps reveal the total failure of the German highly expensive energy policy, inspired by the Green Party since the days of Angela Merkel.

Literally billions of tax payer money has been spent to decarbonize German energy production.
Despite all this money spent, Germany still has one of the dirtiest electricity mixes of Europe.

You should carefully check the data you will receive after this "pause". I'm sure they will look significantly "cleaner" than the data you have received so far. And I'm sure the Green Party will have a close eye on these data after the publication in "Bild" (Thank's a lot @hallyday2023 for the link!)

Of course, you, VIKTORVAV99,  will delete this entry, because it is "off-topic". If that makes you feel good, so be it!

**Comment by VIKTORVAV99** [comment]
> Of course, you, VIKTORVAV99, will delete this entry, because it is "off-topic". If that makes you feel good, so be it!

First of all there is a difference between marking these as off topic and deleting them. Marking them as off topic still allows them to be viewed, something I feel is important for accountability on both sides, they just minimize to a default minimized state.

I do not condone or appreciate you trying to make this personal or political. This issue is for discussing and informing people about the technical issues, updates and solutions to the issue at hand. It's not a discussion board for any political agenda on either side. There is plenty of other forums for that.

So yes I will be marking it as off-topic because people that are following this issue for technical updates do not need to see political agendas from either side of the discussion.

**Comment by hallyday2023** [comment]
Sure marking comments as off-topic is much better than deleting them. But only readers that are registered can then read them.
Concerning politics: do you believe in coincidence? It is very strange that exactly after the bild.de article and also a users comment to an article on welt.de Germany lost its data. I assure you that the green party really hates to see this bad Co2 data especially compared to France that achieves very good Co2 results due to nuclear power. As @ReneMacon pointed out the head of Bundesnetzagentur is member of green party and probably has enough influence to block the data. Since people from green party are quite ideological I also suspect that they would do such disrespectful things.

**Comment by VIKTORVAV99** [comment]
> Sure marking comments as off-topic is much better than deleting them. But only readers that are registered can then read them. Concerning politics: do you believe in coincidence? It is very strange that exactly after the bild.de article and also a users comment to an article on welt.de Germany lost its data. I assure you that the green party really hates to see this bad Co2 data especially compared to France that achieves very good Co2 results due to nuclear power. As @ReneMacon pointed out the head of Bundesnetzagentur is member of green party and probably has enough influence to block the data. Since people from green party are quite ideological I also suspect that they would do such disrespectful things.

It was not only Germany data that was "lost" in after the maintenance update, in fact only one German TSO was affected but that means no aggregate level data for Germany was able to be published.

Here is the full list of affected areas as listed by ENTSO-E: RO, DE(TenneT), SE, LT & HU

All but DE(TenneT) have since recovered.

I once again ask that you keep political agendas out of this as this is not the forum for such discussions.

**Comment by hallyday2023** [comment]
But what is the reason that the countries RO, SE, LT & HU have not been grayed out on the map at any time?
And why does DE(TenneT) not recover since 4 days?

**Comment by dephira** [comment]
> But what is the reason that the countries RO, SE, LT & HU have not been grayed out on the map at any time? And why does DE(TenneT) not recover since 4 days?

What will be your excuse once the DE data is restored?

**Comment by jarek** [comment]
For the record, I have marked two most recent messages from hallyday2023 as hidden just now.

I am not feeling as charitable as Viktor, so please knock it off or I will delete any follow-up messages that do not directly reference peer-reviewed science.

**Comment by w-flo** [comment]
On a more general note, and hopefully keeping the discussion on-topic about "German data is missing": Missing data for Germany is a pretty common occurence. There are at least 5 parties involved in the data collection process (Entso-E, Amprion, TenneT, 50 Hertz, TransnetBW) and surely each of the 4 Geman TSOs has a plethora of lesser known parties and processes they receive data from. We have to consider that "timely delivery of data to Entso-E" is not their actual income source, so maybe their IT systems for that task are not the most robust, and priorities in IT departments are elsewhere.

For example, just one month ago, we had another week-long outage for German data: #5422 It was slightly different because it was caused by TransnetBW, not TenneT, which means that lignite and offshore wind data was still available. Also, electricitymaps didn't gray out Germany on the map back then and instead relied on their Estimation method (which of course can't really work great without any somewhat recent data, so the resulting CO2 emissions were far too high back then, which was of course useful for some in political discussions – so I definitely support disabling a country instead of estimating data for prolonged time periods).

Or last year, we had Amprion failing for a week or so in #3732 And now it's TenneT that is missing, but from the Entso-E update messages, it sounds like the issue is on Entso-E's side of that API.

So this is totally normal. If you need access to yearly data like I was originally trying to do in this bug report, you can check out the [Umweltbundesamt website](https://www.umweltbundesamt.de/themen/co2-emissionen-pro-kilowattstunde-strom-stiegen-in) where they have yearly data. (Of course, this is run by another one of the "green ministries" more or less directly, so it may not be for everyone.)

**Comment by madsnedergaard** [comment]
Thanks for the detailed explanation @w-flo! 🙌 
 
To elaborate on **why we decided to disable Germany** specifically: we did indeed have our estimation model fill in at first, but due to changing weather patterns the results of the estimation model was starting to drift too far off. It was showing Germany with a much lower wind production than in reality and therefore also a much higher carbon intensity.

So we decided that it would be better to stay true to our integrity and show nothing instead of showing inaccurate data.

Lastly, this is the latest information we have received from ENTSO-E yesterday:

![Screenshot 2023-06-22 at 10 21 55](https://github.com/electricitymaps/electricitymaps-contrib/assets/3296643/3348519e-17ff-43c2-8a8d-e1e5df54ff7c)

**Comment by hallyday2023** [comment]
Why is this comment spam?

But what is the reason that the countries RO, SE, LT & HU have not been grayed out on the map at any time?
And why does DE(TenneT) not recover since 4 days?

**Comment by madsnedergaard** [comment]
FYI, the maintenance was scheduled and mentioned 2 weeks ago for anyone thinking it "suddenly happened": 
![Screenshot 2023-06-22 at 15 49 04](https://github.com/electricitymaps/electricitymaps-contrib/assets/3296643/6133391e-14ef-40ac-a997-3b4b9d5bc184)

**Comment by hallyday2023** [comment]
I agree that maintenance was planned. But it was not planned to have Germany as white spot for now already nearly a week.

**Comment by hanskaas** [comment]
könnte ja auch sein, dass diese Seite Herrn Habeck irritiert, führt sie doch seine ganze Wendepolitik ad absurdum. Da wird eifrig aus den grünen Staaten imortiert und an braun und schwarz exportiert. Gut für den deutschen Schnitt

**Comment by Chungaa** [comment]
Leute, Deutschland hat es nicht so mit der IT. Bis sie das Problem aus ihren System beheben wird es eine sehr lange zeit dauern. Wir müssen uns daran gewönnen das, das nicht gleich funktioniert.

**Comment by hallyday2023** [comment]
Still no data from TenneT? Is no data available or are there problems with transmitting the data. Nevertheless it is a big mess that Germany is a white spot since a week.

**Comment by w-flo** [comment]
There is no official word on it yet, but looking at the data, it seems to be back on track for the country-level aggregation, the bidding zone DE+LU, and the TenneT (DE) data. Might be slightly delayed but seems to be catching up nicely. Might be good enough to enable Germany on electricitymaps again?

Also, the statements published by Entso-E on the transparency platform website read like TenneT couldn't do anything to speed up fixing this. It seems like something that needed to be fixed on Entso-E's side this time, even though it only affected some of the TSOs.

So hopefully this issue can be closed soon to maybe stop the silly "Habeck secretly forced Entso-E (or TenneT) to stop their publishing of data that they are required to publish by law" "_discussion_".

**Comment by VIKTORVAV99** [comment]
Germany have now been enabled again as data is flowing and has been backfilled.

I will be closing and locking this issue now as the problem has been resolved.
