### ISSUE TITLE
Serbia Data not correct

### ISSUE THREAD

**Issue by Chungaa** [electricitymaps/electricitymaps-contrib#5549]
The data given for Serbia is not correct, once it says 6GWh and once it says that it is 20GWh. I am 1000% sure that this can not be true, please remove this, because you do not have correct data.

Watch also times with the wind energy once it shows that it has more capacity, and once it shows that it has less capacity.

All this can not be true.

![Screenshot_2023-07-02-10-51-19-67_d55807758cc388fd9c1f47cb01ea0747](https://github.com/electricitymaps/electricitymaps-contrib/assets/109001366/a89ff94c-b7b7-4ef4-b202-fe5b9457b5f0)

![Screenshot_2023-07-02-18-30-53-41_d55807758cc388fd9c1f47cb01ea0747](https://github.com/electricitymaps/electricitymaps-contrib/assets/109001366/9131b2c8-bc8a-44e3-9f6b-02a45523db5b)

**Comment by VIKTORVAV99** [comment]
Hi and thanks for opening the issue!

These values are collected directly from [ENTSO-E Transparency platform](https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show) where they already have been corrected so they should update in the app as soon as when the next hour starts.

Hopefully they can fix the issue on their side so this don't happen but since that is out of our control I'll look into and see if we can add some validation on our side as well.

**Comment by VIKTORVAV99** [comment]
Closing as the data has now been updated in the app.
