### ISSUE TITLE
Wrong data in Spain<->Morocco connection

### ISSUE THREAD

**Issue by silimotion** [electricitymaps/electricitymaps-contrib#5645]
## Description
Just as I suspected, the data for the Spain<->Morocco connection is wrong, as can be seen on the [ESIOS webpage](https://www.esios.ree.es/en/analysis/10209) (ignore the lack of data during last night, that's not linked to this).
It is related to the fact that the parser returns MWh of fifteen minutes intervals, while the backend expects MW, so averages instead of adding.
Apart from changing something in the backend, the easiest solution that I found is forcing the API to return hour intervals. We would have to add a small delay also, to prevent returning incomplete data. (e.g. server only adds 11:00 and 11:15 if the provided date is 11:24)
We could alternatively multiply the 15 minutes interval data by 4 to get the MW. This would increase the granularity but would imply adding specific cases for this exchange, the parser would break if the granularity ever changes, etc. Whereas by forcing the granularity to 1 hour we make sure the granularity is always correct.
What is your opinion?

**Comment by VIKTORVAV99** [comment]
I think we would have to use 15 minutes values going forward otherwise only every 4th value would be overwritten in the database.

So adding a function to multiply it by 4 is probably the best option. I think adding a table similar to the one we did for the ID but with multiplication factors. That way we could support hourly down to per minute if needed.

I'll try and take a look at it later today as well.

**Comment by silimotion** [comment]
I can work on a PR to add the table if you will.

**Comment by VIKTORVAV99** [comment]
> I can work on a PR to add the table if you will.

That would be great! 🎉

**Comment by VIKTORVAV99** [comment]
I will re-fetch all data as soon as the new version of the app is deployed.
