### ISSUE TITLE
[Data Issue]: Add Rajasthan

### ISSUE THREAD

**Issue by Manu1400** [electricitymaps/electricitymaps-contrib#5676]
### When did this happen?

[rajasthan](https://sldc.rajasthan.gov.in/rrvpnl/rajasthan-overview)

Scada Name | Value | Date time
-- | -- | --
DSM RATE | 123.48 | 1 Aug 2023 12:30:46
FREQUENCY | 50.08 | 1 Aug 2023 12:30:46
NR SCHEDULE | 2223.17 | 1 Aug 2023 12:30:46
NR DRAWL | 1932.88 | 1 Aug 2023 12:30:46
NR OD/UD | -290.29 | 1 Aug 2023 12:30:46
OWN GEN | 10280.69 | 1 Aug 2023 12:30:46
RAJ DEMAND | 12213.57 | 1 Aug 2023 12:30:46
SOLAR GEN | 3484.56 | 1 Aug 2023 12:30:46
WIND GEN | 1150.02 | 1 Aug 2023 12:30:46
BIOMAS | 18 | 1 Aug 2023 12:30:46

### What zones are affected?

maybe IN-NO? IN-RJ?

### What is the problem?

Add some real-time live (± few mn) data about Rajasthan

**Comment by VIKTORVAV99** [comment]
Wile it would be nice to get higher granularity data I'm a bit unsure we can do this as is.

Mostly because the Indian zones use a set of estimation models to compute the hourly values (from daily values I believe). So integrating a new zone in India is not as straight forward as other zones.

@unitrium and @mathilde-daugy what do you guys thing?

**Comment by madsnedergaard** [comment]
Since we cannot get good enough data for all states, we are going to switch away from the state-level India parsers and instead use larger regions (the zones you see on the map now, e.g. "Northern India", "Western India", etc.).
These will mostly be covered by our internal estimation models to improve the power breakdown accuracy and ensure we're able to show more recent data on the map :)
