### ISSUE TITLE
Not matching values, error in country name.

### ISSUE THREAD

**Issue by Michael0137** [electricitymaps/electricitymaps-contrib#5689]
![Bildschirm­foto 2023-08-01 um 20 50 17](https://github.com/electricitymaps/electricitymaps-contrib/assets/141178405/474cd662-0727-4801-b4a8-b269e021c6ed)
As shown, the country name is not eligible and the indicated imported power is not matching the percent value.
Regards
Michael

**Comment by jarek** [comment]
The imported power shown as 594 MW seems to be a weird glitch, I am wondering if it was something temporary? This is how it looks for me right now:

![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/47415/c5314108-277c-4535-b397-46ce3589ab21)

(21:00 in my timezone is 03:00 German time)

I'm seeing 3.54 GW for that time now, which matches 8.34% of 42.8 GW (8.32% in your screenshot but that might have been due to some small amount of data arriving late?).

It might have been a front-end glitch which caused an old value or value for other source to be shown in that box. Can you let us know if this kind of problem is still happening for you?

The garbled country name could be related to fonts or rendering. Can you share your operating system, browser, and device type? Does this happen always or only sometimes?

**Comment by Michael0137** [comment]
The problem is still there, even after a restart of Safari.

The language is German, i am using Safari Version 16.3 (18614.4.6.1.6) on a MacBookPro with MacOS 13.2.1 (22D68).

It seems to be a Safari problem. With Firefox, the data and font are OK.

**Comment by madsnedergaard** [comment]
I can reproduce this in Safari with multiple languages, it is very strange bug indeed 😅 

https://github.com/electricitymaps/electricitymaps-contrib/assets/3296643/6c5f5a8f-4dad-4959-a825-efe1816b2096

Will look into it and see if I can fix it!
