### ISSUE TITLE
South Korea data doesn't seem right

### ISSUE THREAD

**Issue by silimotion** [electricitymaps/electricitymaps-contrib#5845]
## Description
I've noticed that South Korean data does not match the source, nor the results of running the parser locally. There aren't errors in the logs neither. The app shows that some data is being estimated:
![Screenshot_20230910_213433](https://github.com/electricitymaps/electricitymaps-contrib/assets/84802276/dcda6847-b7cd-4ae0-8ae9-23071837c338)
![Screenshot_20230910_213642](https://github.com/electricitymaps/electricitymaps-contrib/assets/84802276/182bea7e-021b-467c-b1ea-20bd4d13350a)
![Screenshot_20230910_213851](https://github.com/electricitymaps/electricitymaps-contrib/assets/84802276/9e8e67a6-d7a6-43fa-a704-a7a46d626911)
It is especially notable in the fact that nuclear should be a stable line but it is load following in the app. The parser seems to be getting the data correctly (~20GW nuclear). It seems the problem is in the backend, possibly in the estimation model. It seems that the estimation is needed to transform "renewables" in the graph to the different production types of the app, but it is not functioning correctly as the graphs don't match.

**Comment by alixunderplatz** [comment]
Hey @silimotion , can you post the link to the website of your graph? is that a near-real-time graph of an official Korean source?

**Comment by silimotion** [comment]
Hi @alixunderplatz, the graph is from [https://new.kpx.or.kr/powerSource.es?mid=a10606030000&device=chart](https://new.kpx.or.kr/powerSource.es?mid=a10606030000&device=chart). I found this link in the KR.py parser. For real time data the parser uses [https://new.kpx.or.kr/powerinfoSubmain.es?mid=a10606030000](https://new.kpx.or.kr/powerinfoSubmain.es?mid=a10606030000), which contains a similar graph, but locked to the present day. I used the graph form the first link because it clearly showed the data for the whole day. Hope this is uesful!

**Comment by silimotion** [comment]
Comparing the current chart with a screenshot from when the parser was made (#3676) shows that new types of production have been added since, such as solar. This may not be related, though.

**Comment by jarek** [comment]
Something's definitely up. Electricity Maps is using estimates for the past 24 hours, even though data is available on the official website and no errors are logged in https://storage.googleapis.com/electricitymap-parser-logs/KR.html

Looking at the source code, one thing that jumps out at me is that fetch_production can call one of two different functions, `get_granular_real_time_prod_data` and `get_long_term_prod_data`, and the `get_long_term_prod_data` function hardcodes indexes for parsing the data table. This likely needs updating, and maybe a rewrite so that columns are parsed by title rather than by index?

I'm also not sure if the condition switching between those two functions, `if target_datetime.date() == arrow.now(TIMEZONE).date()`, makes sense? Wouldn't it do different things when Korean time and server time or UTC aren't on the same date, so for about a third of the day? Is this really desired?

I will ping in people who wrote and reviewed the parser, maybe they can comment? @IV1T3 @madsnedergaard

**Comment by madsnedergaard** [comment]
Thanks for the ping :)

Back in 2021 we chose to use an estimation model to cover South Korea (KR) due to problems with the data source. Here's our findings at the time:

<img width="708" alt="Screenshot 2023-09-11 at 07 52 27" src="https://github.com/electricitymaps/electricitymaps-contrib/assets/3296643/22c7ba47-a103-4eae-b86e-5a70ce4a649d">

The data and parser was later improved a lot in 2022, but since we had API customers relying on the old data we couldn't just change it at that point.

A lot has changed since then though, so what are you thoughts on this @pierresegonne? I can see on [ELE-886](https://linear.app/electricitymaps/issue/ELE-886/update-kr-model-after-new-parser-change) that you added a checked todo item "Set up a reminder to re-create an issue to deactivate RB on KR", but I couldn't find the reminder anywhere 😅

**Comment by pierresegonne** [comment]
Thanks for the ping @madsnedergaard let's look at it this week :)

**Comment by VIKTORVAV99** [comment]
Just to provide an update, we are refetching as much data as we can and will switch from the estimations to parser data as soon as that is done.
