### ISSUE TITLE
Production over 100% in consumption mode

### ISSUE THREAD

**Issue by IntermittentNRG** [electricitymaps/electricitymaps-contrib#5973]
### When did this happen?

always

### What zones are affected?

SE-SE1, SE-SE2

### What is the problem?

[SE-SE2](https://app.electricitymaps.com/zone/SE-SE2) produces above 200% renewables as share of consumption.

In SE-SE2 2022
- hydro provided 266% of the electricity consumed
- wind provided 95.31%.
This is not reflected in renewable % share.

I realize more than 100% doesn't make sense, but this is actually how we are counting. It should not be artificially capped at 100%.

If a region can be 100% renewable (of consumption) with non-renewable generation, then it should also continue beyond 100% (of consumption).

**Comment by VIKTORVAV99** [comment]
These are two different metrics and we recently changed the production / consumption one.

Now exports are taken into account in the consumption metric so when the sum of sources produce more than 100% it means the overshooting parts are used in exports, something you can clearly see for SE-SE1 and SE-SE2.

The second metric is how much of this share is actually from low carbon or renewable sources.

I hope this give some clarity on the matter.

cc @madsnedergaard

**Comment by IntermittentNRG** [comment]
I do have clarity. While % of consumption can be a useful metric, it's also misleading.

- With low demand and high renewable output it can be 100% of consumption while coal/gas are generating GWs of output.
- On a yearly basis renewables can be 100% of consumption while on some days it was 0%.

The total is not 100%. I think the least we can do is uncap it so it can go above 100%.

**Comment by intermittentnrg** [comment]
My complaint here though is that if this counts as 99% renewable (of consumption) as claimed by Mark Z Jacobson on X. Then what happens if we further increase? ![99% renewable graph](https://pbs.twimg.com/media/F0yoewYWcAIJyuD?format=jpg&name=large)


![Claim by Mark Z Jacobson](https://pbs.twimg.com/media/F0sMaYTaQAUpv9p?format=jpg&name=900x900)
The renewable % of consumption is a totally misleading figure. The total generation is more than 100% (of consumption).
Source: https://twitter.com/IntermittentNRG/status/1678903251922460676

Frankly it should perhaps not be used. But it does have some use, and the least we can do is uncap it to go above 100% as people think 100% means it's clean while gas plants are firing at 5GW output.

So it's with some smug satisfaction I say that Sweden is 120% low carbon or that SE-SE2 is 223% renewable and they have a long way to go after they reach 100%.

**Comment by VIKTORVAV99** [comment]
Our app (and API) would not show that. It doesn't use a net calculation but rather a total share of production. If there is 99% renewable with 5GW gas production it means there also is 495 GW renewable energy. Something California can't achieve so we will never show 99% renewable power for California if they are generating those sums of non renewable electricity.

And since we use a share model it can never go above 100% and this is not something we are going to change.

**Comment by intermittentnrg** [comment]
Aha, awesome, thank you, then it's correct, sorry for my misunderstanding.
I did not realize different methods are being used to calculate renewable share of consumption.
