### ISSUE TITLE
county info ℹ️ button broken on mobile

### ISSUE THREAD

**Issue by q--** [electricitymaps/electricitymaps-contrib#6035]
**Describe the bug**

**To Reproduce**
1. Go to any country with an info button in the app or browser (tested on my phone); e.g. https://app.electricitymaps.com/zone/CH?wind=true
2. Tap the `(i)` button at the top right
3. Nothing happens

**Expected behavior**
A dialog should've appeared with some important note about the displayed data.

**Smartphone (if relevant):**
 - OS: Android
 - Browser: Firefox; also reproduced in the app

**Comment by VIKTORVAV99** [comment]
I can confirm it is also broken on the iOS app in the latest build (and likely has been all along).

**Comment by madsnedergaard** [comment]
The issue is that it is a tooltip, so it will only work on `:hover` - I can't remember why it was done like this though 🤔 

<img width="433" alt="Screenshot 2023-10-23 at 07 17 33" src="https://github.com/electricitymaps/electricitymaps-contrib/assets/3296643/45e93743-066b-43a8-af36-1c7622ef1d31">

Should be fairly doable to just change it to something that can be triggered by click on touch devices.

**Comment by tonypls** [comment]
This is because we use the radix tooltip component which by default only works with :hover. We do also have a mobile tooltip wrapper, we could either use  conditionally use the mobile tooltip wrapper here or implement our regular tooltip wrapper to work with both tap or hover (easier said than done 😉 )

**Comment by q--** [comment]
While I think it would be best to make the button work (on mobile) first, it's also worth asking if having a button with an icon is sufficient to communicate sometimes significant data caveats; if it's always been broken and nobody bothered reporting it up to now, it makes me wonder how many people actually read the information there.

**Comment by VIKTORVAV99** [comment]
This works on mobile now :)
