### ISSUE TITLE
sort production graph by "stability" in the "generation over the last 24 hours"

### ISSUE THREAD

**Issue by Marc-marc-marc** [electricitymaps/electricitymaps-contrib#6051]
**Is your feature request related to a problem? Please describe.**
Looking at the [Belgium production](https://app.electricitymaps.com/zone/BE) "generation over the last 24 hours" (left side pannel) today 26/10/2023 using a web browser, I don't really appreciate the variation in gas production, which is on top of solar production, which varies much more than gas production.

**Describe the solution you'd like**
sorting/stacking generation resources according to their variability, i.e. in this case from bottom to top
solar on top (currently under gas)
gas in the middle (currently on top)
nuclear-biomass (unchanged from the current situation).

This would give a better idea of the variability of the different resources of production.

**Describe alternatives you've considered**
ability to select and have a graph forr one-only resource (for ex like eCO2mix allow)

**Additional context**
feel free to tell me if you need screenshot about what i'm talking about (and thanks for this great tool)

**Comment by tonypls** [comment]
Hi @Marc-marc-marc,

Thanks for bringing this up! 

Currently the order has [dispatchable](https://en.wikipedia.org/wiki/Dispatchable_generation) generation on top.

We're also currently having discussions on how to order things in the horizontal breakdown chart here #4109 

To me the dispatchability does make sense for the over the last 24 hours chart as it shows how the gaps in demand are filled with controllable production sources but I'm open to be convinced otherwise.

**Comment by madsnedergaard** [comment]
Closing this in favor of #4109 so we keep conversation in one place :)
