### ISSUE TITLE
EU countries missing Prices

### ISSUE THREAD

**Issue by asfi30** [electricitymaps/electricitymaps-contrib#6232]
## Description
Hi All,

I see some countries or Zones in EU are missing the prices in EUR/MWH. On the following link 
https://newtransparency.entsoe.eu/market/price/dayAhead/PT60M?appState=%7B%22sa%22%3A%5B%22BZN%7C10YCA-BULGARIA-R%22%5D%2C%22st%22%3A%22BZN%22%2C%22mm%22%3Atrue%2C%22ma%22%3Afalse%2C%22sp%22%3A%22HALF%22%2C%22dt%22%3A%22TABLE%22%2C%22df%22%3A%5B%222023-12-08%22%2C%222023-12-08%22%5D%7D 

You can actually get the Day-Ahead Price that is the hourly price in EM. You can even Copy/Create QR code or send to your device each bidding zone/country. I wonder is it possible to use this data and incorporate the Prices in EM as well. Not sure if it has to be manually that will take some time and not automatically. Probably something like the "estimate". In any case it is Day ahead and it is available from 2PM EET(+2GMT). So what  can be done in my view is that you can pre-upload the prices and display accordingly. Hope this makes sense.

Regards,
Aleks

**Comment by VIKTORVAV99** [comment]
Hi!

We are already collecting the price data from ENTSO-E via the API to use internally but the ENTSO-E license specifically states that we are not allowed to republish the price data unfortunately so this is not something we can do right now. See https://github.com/electricitymaps/electricitymaps-contrib/issues/5036 and https://github.com/electricitymaps/electricitymaps-contrib/issues/5128.

We are however exploring other options but I have nothing to share in this area yet.

Since this is not something we can do at the moment I will close the issue in favour of the second one I linked instead.
