### ISSUE TITLE
[Data Issue]: MISO generation mix wrong/missing/estimated despite parser being available

### ISSUE THREAD

**Issue by somedatapacket** [electricitymaps/electricitymaps-contrib#6292]
### When did this happen?

2023-12-16 12:45

### What zones are affected?

US-MIDW-MISO

### What is the problem?

There is no wind/solar renewables data available despite MISO providing this generation mix breakdown. This is resulting in inaccurate information for e.g. MISO Zone 7 as only coal, natural gas, and nuclear generation estimates are available.

**Comment by VIKTORVAV99** [comment]
Hi and thanks for opening the issue!

We are currently using EIA to fetch this data and they seem to be having some issues as the parser currently returns no data at all for the last few days (since 2023-12-22T04:00Z), we expect this to be fixed but we don't know when. But when it is our systems will refetch this missing data and correct it.
