### ISSUE TITLE
[Data Issue]: Large change in estimation model output at the start of the new year

### ISSUE THREAD

**Issue by q--** [electricitymaps/electricitymaps-contrib#6307]
### When did this happen?

00:00 UTC, January 1st, 2024

### What zones are affected?

Estimated zones; I observed it for the Netherlands and Sri Lanka 

### What is the problem?

Estimates shouldn't change so radically at the start of a new year.

Netherlands: ![Screenshot_20240101-224143](https://github.com/electricitymaps/electricitymaps-contrib/assets/2470175/d55e0dd3-57bd-4dd3-b798-cb685ee70749)

Sri Lanka: 
![Screenshot_20240101-224233](https://github.com/electricitymaps/electricitymaps-contrib/assets/2470175/cb70e1a4-a54d-46d4-b5db-9f489c0e89dd)

Note that the entire timespan that I could choose from showed the "estimated" label for LK, so it's not a matter of actual data vs estimated.

**Comment by VIKTORVAV99** [comment]
Thanks for opening the issue!
I noticed this too and will be adding an internal issue for it as well.

**Comment by q--** [comment]
You're welcome. Happy New Year by the way, and I hope you had a good Christmas as well!

**Comment by VIKTORVAV99** [comment]
> You're welcome. Happy New Year by the way, and I hope you had a good Christmas as well!

Thanks for the considerations, I had a both a good Christmas and New Years and I hope you did as well!

**Comment by mathilde-daugy** [comment]
Looks like the issue resolved itself for NL,  we were probably getting poor quality data fed into our estimation model 😅 
![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/107848894/600fe669-a326-49af-9262-a975fa524060)

Similarly for LK, the data was updated and the issue was fixed 
![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/107848894/937882e4-9f41-4a98-a19a-67b165c8af6f)


I will close this issue but make a note of this issue for the future :)
