### ISSUE TITLE
[Data Issue]: BD imports are counted as generation in source

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymaps/electricitymaps-contrib#6542]
### When did this happen?

Ongoing since start?

### What zones are affected?

BD

### What is the problem?

It seems like the source is including imports as generation but we do not, so where are inferring an unknown production that is almost 1=1 with the imports. The parser needs to be updated to account for this and then all data needs to be re-fetched and reprocessed.

**Comment by q--** [comment]
Small thing I noticed after I pointed this out in https://github.com/electricitymaps/electricitymaps-contrib/pull/5381#discussion_r1493420553 is that, for a _few_ data points, generation data is incomplete (e.g. a bit of gas generation appears to be unreported); in that case 'unknown' is not only imports. Otherwise it's all imports like you've described. 

(I can look for a screenshot for the day I noticed this if it helps. I don't know if it happens often or if it's corrected automatically when data is re-fetched, I just wanted to point out that, _sometimes_, this happens.)

**Comment by VIKTORVAV99** [comment]
> Small thing I noticed after I pointed this out in [#5381 (comment)](https://github.com/electricitymaps/electricitymaps-contrib/pull/5381#discussion_r1493420553) is that, for a _few_ data points, generation data is incomplete (e.g. a bit of gas generation appears to be unreported); in that case 'unknown' is not only imports. Otherwise it's all imports like you've described.
> 
> (I can look for a screenshot for the day I noticed this if it helps. I don't know if it happens often or whether it's corrected automatically when data is re-fetched, I just wanted to point out that, _sometimes_, this happens.)

Any additional information would be helpful!
I also noticed that for some datapoints there is actually unknown production but I have only seen single digits.

**Comment by q--** [comment]
I've added a screenshot to my comment
