### ISSUE TITLE
Europe: Improve emission factors with 2023 data and better mapping

### ISSUE THREAD

**Issue by madsnedergaard** [electricitymaps/electricitymaps-contrib#6581]
## Description

We are aware that the current emission factors based on EU-ETS could be improved further.

See past discussions here: https://github.com/electricitymaps/electricitymaps-contrib/issues/5417
And the great work by @w-flo here: https://github.com/w-flo/eu-emission-factors/tree/main

This issue is intended to gather knowledge and details about how we can improve this further for next time we can update the numbers, as EU-ETS is supposed to release new data quite soon (during April as far as I can tell).

**Comment by w-flo** [comment]
EU-ETS data is now available for 2023 ([under "Documentation"](https://climate.ec.europa.eu/eu-action/eu-emissions-trading-system-eu-ets/union-registry_en)).

As I see it, there are three issues:
- It's difficult to map Entso-E electricity production data to the corresponding EU-ETS emissions data. Some automatic mapping based on power plant names is possible, but only in somewhat lucky cases. I have the manual_matches.csv file in the repo you linked as a best-effort manual mapping for cases where the automatic attempt fails, but that's not really straight-forward either and probably has some incorrect entries (e.g. sometimes smaller units / turbines of a power plant are missing from Entso-E, but EU-ETS reports emissions for all units of the power plant). Still, I'd say it's possible to mostly solve this issue by using something like my manual_matches.csv file and manually filtering plants where units are missing etc.
- How to handle combined heat and power plants (CHP). A simple "emissions divided by production" calculation is not the right approach in this case, because some emissions should be attributed to heat provision instead of electricity production. However, I couldn't find a data source for the amount of heat provided by each CHP plant per year, so finding a solution for this problem is difficult. I'm not convinced by my attempted solution in the linked repo. As I understand it, it is possible to extract the amount of heat provided by each ETS power plant in the baseline period (2014 to 2018) from the ETS "free emission allowances" allocation. However, using that old data for current years might be problematic, and I'm not sure how this works with new power plants (I think they use some kind of estimation in their first year, and then recent data instead of data from 2014 to 2018?). Related to this, some CHP plants provide heat (and/or steam) to nearby industry. If that industry needs to use ETS itself, the power plant won't receive free emission allowances for that heat, so the estimation based on that "allocation" fails. Another case for manual filtering.
- Small power production units (<100 MW) do not publish any unit-level data in Entso-E or emissions data to ETS. For example, in 2023, my tool reports that Germany produced 28.8 TWh of gas power based on Entso-E unit-level data (29.1 TWh according to [energy-charts](https://www.energy-charts.info/charts/energy/chart.htm?l=de&c=DE&interval=year&year=-1&source=fossil_gas_unit_eex)). However, [total gas power production in 2023 was 50.1 TWh according to Entso-E](https://www.energy-charts.info/charts/energy/chart.htm?l=de&c=DE&interval=year&year=-1&source=entsoe&legendItems=000000000100000000000). My tool matched 25.3 TWh of unit-level production data to corresponding emissions data, estimating a direct emission factor of 437 g/kWh. But that's based on only one half of the total gas-based electricity production. I don't think it's correct to take this as the (direct) emission factor for all gas power plants in Germany, because we don't know anything about the other half. It would probably be better to weight that number of 437 by a factor of (25.3 / 50.1) and assume some IPCC emission factor or similar for the "unknown" other half of the total German emission factor. Maybe electricity-maps already does this, but I think it didn't a few years ago.

Of course, the same applies to coal and oil. At least coal is slowly going away and oil is rarely used.

**Comment by cgicgi** [comment]
awesome work and explanation, thank you!
Small correction: [energy-charts](https://www.energy-charts.info/charts/energy/chart.htm?l=de&c=DE&interval=year&year=-1&source=fossil_gas_unit&legendItems=000000000100000000000) reports 27.2 TWh based on Entso-E unit-level data (your link points to EEX as data source with the mentioned 29.1 TWh)

**Comment by madsnedergaard** [comment]
Thanks for sharing the update @w-flo, we are planning on addressing this soon and updating the numbers - hopefully we can include your great work! We will get back in touch soon :)

**Comment by madsnedergaard** [comment]
This list ([shared here](https://x.com/HMitterwald/status/1791027876659105827)) might be useful to look at what power plants are active:

https://www.bundesnetzagentur.de/DE/Fachthemen/ElektrizitaetundGas/Versorgungssicherheit/Erzeugungskapazitaeten/Kraftwerksliste/start.html

**Comment by madsnedergaard** [comment]
**An update here:**

We are actively working on this project these days!

We are going to:
- [x] Use 2023 ETS and ENTSOE data
- [x] Use the great mapping of power plants from @w-flo in addition to our own mapping
- [x] Update the heat allocation numbers
- [x] Improve the notebook used for calculating the EU emission factors
- [ ] Verify differences between our calculations and the ones found by @w-flo 
- [ ] Move the Notebook to this repo so it is more easily findable and up-to-date


I am currently looking into the larger differences found for some zones between our calculations and those in https://github.com/w-flo/eu-emission-factors/blob/main/data/2023/output/countries.csv
Not sure what is causing it yet, but at first I will be digging into the concrete power plants to ensure that we cover all the same ones in an identical way :)

![Screenshot 2024-06-11 at 14 36 30](https://github.com/electricitymaps/electricitymaps-contrib/assets/3296643/3d1a1f55-2a0f-410d-bac2-4f44b2bee2d4)

**Comment by w-flo** [comment]
Cool! Of course I'm available if you have any questions about these CSVs in my repo.

I'm interested in those differences in country-level data, too. I see you're already on it :-) Is the powerplant-level data from electricitymaps available somewhere, maybe as a gist/pastebin?

I don't think I use any sort of fuel mapping, I just [use](https://github.com/w-flo/eu-emission-factors/blob/main/src/preprocess.rs#L143) the ENTSO-E "ProductionType" from the ENTSO-E CSV. If a unit is claimed to be using "Fossil Oil" (that's the string they use for oil units) by ENTSO-E, I count it as oil. I assume the ETS data would indicate lower carbon emissions for that power plant if they actually use bio oil instead of fossil oil, so that lower carbon footprint should hopefully be reflected in the results.

**Comment by madsnedergaard** [comment]
I have made a public Google Sheet here that contains our current (temporary!) calculations compared to yours: https://docs.google.com/spreadsheets/d/1cdHJm_h63taXl9dXiJN7TFG-WAQsGvdHiYp9kuwaE0w/edit?usp=sharing

I also added the plant-level information now, and it's clear that something is off with the code for manual matching (I don't get the same manual matches you did, e.g. only 1 coal power plant for Finland instead of 5). I'll get to work on that today.

Secondly there's also examples where the heat-allocation and therefore emissions are very different:

### w-flo for Finland

| country  | generation     | emission                | fuel | sigma | generation_el | generation_heat | emissions_heat | emissions_el | emission_factor |
| -------  | -------------- | ----------------------- | ---- | ----- | ------------- | --------------- | -------------- | ------------ | --------------- |
| FI       | Salmisaari SaB | Salmisaaren voimalaitos | coal | 0     | 600471.96     | 1478216.339     | 378597.4771    | 351523.5229  | 585.4120531     |

### emaps for Finland

| zone_key | production_mode | installation_name       | emissions | allocation | generation_mw | generation_mwh | heat_emissions | elec_emissions | emission_factor |
| -------- | --------------- | ----------------------- | --------- | ---------- | ------------- | -------------- | -------------- | -------------- | --------------- |
| FI       | coal            | Salmisaaren voimalaitos | 730121    | 59641      | 68.5470274    | 600471.96      | 161191.8919    | 568929.1081    | 947.4699004     |

**Comment by w-flo** [comment]
I expected differences due to the heat allocation thing. I really don't trust my method a lot, there is a good chance I got some of it wrong. And I'm not sure the electricitymaps method is better (I'm not sure how it works). I think we'd need more data to make it work correctly. If I understand it correctly, the "ETS heat allocation" is based on "how much heat did this combined heat and power plant produce in a reference period a few years ago?", so trying to estimate recent heat generation based on that number is problematic.

So I'd say that's pretty much an unsolved problem.

About those missing coal power plants in Finland: Maybe that's a "plausible emission factor range filter"? The missing coal power plants in Finland have surprisingly good emission factors. The Naantalin plant has 116 for example, which would be highly unusual for a coal power plant, but according to a comment in my manual_matches.csv file, it has been converted to a biomass power plant recently (apparently I googled it back then). Same for Vaskiluoto 2, which has an emission factor of 324, but it's not purely a coal power plant, it also has a biomass unit. Maybe electricitymaps filters that because it seems weird to have a plant that claims to be coal-powered and has an emission factor of 324.

Similar issue for Belgium: The Knippegroen plant is missing in the electricitymaps data, maybe because it's a gas-powered plant with an emission factor of 2300. However, it burns process gas (blast furnace gas?) instead of "normal fossil gas", which apparently results in pretty high emissions. Similar to Mittelsbueren 4 in Germany, Velsen in the Netherlands or DK6 in France. Although I'm not 100% sure if it's fair to include these plants, they're tightly coupled with steel manufacturers and maybe some of their emissions should actually be attributed to the steel plants instead of the power plant – so filtering them might actually be a good idea. Not really sure.

**Comment by VIKTORVAV99** [comment]
I wonder if there could also be an issue with these converted plants having changed their reported fuel. That could cause significant changes if it was previously reported as coal and now as biomass for example. Then I expect the coal calculations to be much higher with the removal of the biomass plants.

But we would have to doublecheck with ENTSO-E production data.

**Comment by w-flo** [comment]
Naantali switched to mostly using biomass, thanks to the new unit Naantali B4, in 2017. And Naantali B4 is listed as "Fossil Hard coal" in [Entso-E unit-level data](https://transparency.entsoe.eu/generation/r2/actualGenerationPerGenerationUnit/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=13.06.2024+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=13.06.2024+00:00|CET|DAYTIMERANGE&area.values=CTY|10YFI-1--------U!BZN|10YFI-1--------U&masterDataFilterName=&masterDataFilterCode=&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)&dv-datatable_length=50) as of today. But [this source](https://www.gem.wiki/Naantali_CHP_power_station) says: "Although original plans were for the plant to be co-fired by coal, TSME later said it planned for the unit to be fueled 100% by biomass and waste". ETS data seems to agree with that.

So it is pretty confusing. I'm not exactly sure if this means that Naantali B4 production will be counted as coal in the "generation per production type" ENTSO-E live data, but it hope it does. In that case, Finland should simply have a really good emission factor for their "coal" power production, since it appears to be mostly biomass with just a few old coal blocks mixed in for exceptional circumstances.

**Comment by madsnedergaard** [comment]
We're still actively working on this on the side - we have something close to done, but still going deeper into significant changes on a power-plant level to investigate why they are changing.

As an example of this, I now have a case where 2 coal power plants in Poland are both reported as "-1" emission for 2023 in the EU-ETS dataset, despite no public information about these power plants not being active 🤔 

This is the 2022 data we have:

| year | installation_name                                 | emissions | allocation | generation_mw | generation_mwh | heat_emissions | elec_emissions | emission_factor |
| ---- | ------------------------------------------------- | --------- | ---------- | ------------- | -------------- | -------------- | -------------- | --------------- |
| 2022 | ELEKTROWNIA PĄTNÓW                                | 1184719.0 | -1.0       | 106.407025    | 9.321255e+05   | 0.000000       | 1.184719e+06   | 1270.986524     |
| 2022 | Elektrociepłownia Zakład EC-4 Veolia Energia Łódź | 860421.0  | 83355.0    | 44.425897     | 3.891709e+05   | 198464.285714  | 6.619567e+05   | 1700.941109     |

Without these for 2023, we now get a 15% drop in coal emission factor for Poland... 

I am leaning towards staying with the current 2022 numbers for cases like this, but if anyone has any ideas on a better approach I'd love to hear it :)

**Comment by cgicgi** [comment]
"I now have a case where 2 coal power plants in Poland are both reported as "-1" emission for 2023 in the EU-ETS dataset"
Sounds like a promising business model ...

Is there any way to verify/discuss these numbers with officials from the EU?

**Comment by VIKTORVAV99** [comment]
> "I now have a case where 2 coal power plants in Poland are both reported as "-1" emission for 2023 in the EU-ETS dataset" Sounds like a promising business model ...
> 
> Is there any way to verify/discuss these numbers with officials from the EU?

@madsnedergaard this is what you are looking at right now right?

**Comment by madsnedergaard** [comment]
> "I now have a case where 2 coal power plants in Poland are both reported as "-1" emission for 2023 in the EU-ETS dataset" Sounds like a promising business model ...
> 
> Is there any way to verify/discuss these numbers with officials from the EU?

Good point, I have sent an email to https://www.kobize.pl/ that is listed as the contact point for Poland here https://climate.ec.europa.eu/eu-action/eu-emissions-trading-system-eu-ets/union-registry_en

**Comment by w-flo** [comment]
I've seen missing ETS data with some power plants / countries in earlier years, they tend to be fixed in the next release (i.e. April 2025). Maybe using the previous year's emission factor for these power plants is the best solution. I took the lazy approach and simply ignore power plants with missing ETS data in my repo.

**Comment by w-flo** [comment]
It turns out these two power plants have now apparently reported ETS data, this source appears to update pretty often (i.e. more frequently than once a year):
https://www.euets.info/installation/PL_21
https://www.euets.info/installation/PL_88

The "-1" probably happens when they report too late for the April report.

**Comment by madsnedergaard** [comment]
> I took the lazy approach and simply ignore power plants with missing ETS data in my repo.
I also wanted to ignore them at first, but for PL and BG it made a large, unrealistic change.

> It turns out these two power plants have now apparently reported ETS data (edit: for 2023), this source appears to update pretty often (i.e. more frequently than once a year): [euets.info/installation/PL_21](https://www.euets.info/installation/PL_21) [euets.info/installation/PL_88](https://www.euets.info/installation/PL_88)
> 
> The "-1" probably happens when they report too late for the April report.

That is brilliant, thanks for sharing! 

I have identified 16 relevant entries where emissions are "-1", and I was able to manually find updated values on that website for 12 of those! :)
