### ISSUE TITLE
Greece is partially coloured. Islands are left out

### ISSUE THREAD

**Issue by mpelas** [electricitymaps/electricitymaps-contrib#6592]
## Description
Aegean sea island are Greek but are left without colour. Crete is colorless too. From thasos to Kastelorizo one country as a whole. 
Avoid using incomplete vector layers. Greece is a archipelago country with so many islands worth visiting. 

Regards

**Comment by VIKTORVAV99** [comment]
Hi!

Our zones are not meant to be matched 1:1 with country borders but rather the grid systems. When it was added, and the last time I checked with ENTSO-E late last year, the Greece islands were still not connected to the main grid. Which is why they have been kept separate as the grid conditions of Greece would not actually match what is happening on the island.

If you have information that they have since been combined and that the islands production and consumption is now included in the ENTSO-E data we have no issue merging the zones.

**Comment by gerrykou** [comment]
Hey, yeah makes sense, there is an update on the network and you can find the update on the etsoe grid maps
https://www.entsoe.eu/data/map/
From the grid map, i can see those islands connected:
Crete, Andros, Tinos, Syros, Mykonos, Paros, Naxos.

**Comment by VIKTORVAV99** [comment]
> Hey, yeah makes sense, there is an update on the network and you can find the update on the etsoe grid maps
> 
> https://www.entsoe.eu/data/map/
> 
> From the grid map, i can see those islands connected:
> 
> Crete, Andros, Tinos, Syros, Mykonos, Paros, Naxos.
> 
> 

I can see that they have indeed made some progress which is great!
I still see that some of the lines are dotted which means they are under construction but I'll send an email to ENTSO-E double checking the status and if the reported production now contains these islands.
