### ISSUE TITLE
Double tapping on mobile causes arrows to disappear

### ISSUE THREAD

**Issue by jackson-dahl42** [electricitymaps/electricitymaps-contrib#6753]
**Describe the bug**
On the mobile version of the app the arrows and wind layer disappear when you tap the screen once or double tap (zoom in).

**To Reproduce**
1. Toggle the wind layer.
2. Tap the screen once or double tap.

**Screenshots**
[Video of bug](https://drive.google.com/file/d/17ta6rvGJa-trxLkas0J9hNODy2wCeqJx/view?usp=sharing)

**Expected behavior**
I think when you tap the screen once or double tap the wind layer should still be their. This is how the app behaves on my laptop because if you click the screen once the wind does not disappear and if you click the screen twice to zoom the wind shows up again.

**Smartphone (if relevant):**
 Samsung Galaxy S20
The bug is on mobile with the native app and the web app (chrome and Firefox)

**Comment by james-guerra-medmate** [comment]
Just FYI, I quickly investigated this and it appeared to be a an issue caused by the `onTouchStart` event from `react-map-gl`.
Line 345 of `web/src/features/map/Map.tsx`.

I was able to replicate the bug using the instructions above and played around with the code by removing the touch event and it fixes the bug. Here's a [screen recording](https://jam.dev/c/a011005b-d176-4c4e-85e6-2cdb17015337) of the solution in action (apologies if the video looks confusing - the first 10 seconds is me replicating the issue and the remaining is the fix, after I remove the touch event)

I'll create a PR.
