### ISSUE TITLE
Dynamically compute emission factors per country per year

### ISSUE THREAD

**Issue by LucBerge** [electricitymaps/electricitymaps-contrib#6805]
**Is your feature request related to a problem? Please describe.**
Russian gas does not have the same carbon footprint than LNG from US or Qatar.

**Describe the solution you'd like**
It would be awesome to dynamically compute the emission factors depending on the gas origin. Same for coal, fuel oil, and uranium.

**Describe alternatives you've considered**
If the lack of data is a problem (or the concistency of the data sources), a solution could be to manually update the emission factors per region each year.

**Additional context**
Germany is importing way more LNG than ever before. I suspect the German carbon footprint to be undervalued.

**Linked issues**
https://github.com/electricitymaps/electricitymaps-contrib/issues/5417
https://github.com/electricitymaps/electricitymaps-contrib/issues/6581

**Comment by VIKTORVAV99** [comment]
Hi!
We would love to do this but unfortunately I don't think we have neither the capacity nor enough data for it currently. We are however in the process of updating the yearly emission factors using the methodology we already have in place.

Once that is done we can take another look at this.
cc @madsnedergaard

**Comment by madsnedergaard** [comment]
> It would be awesome to dynamically compute the emission factors depending on the gas origin. Same for coal, fuel oil, and uranium.

We generally already do this for cases where electricity produced in one country is exported to another.

For LNG specifically it would be nice, but we unfortunately don't get LNG data in [ENTSO-E](https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=true&viewType=TABLE&areaType=BZN&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=10.06.2024+00:00%7CCET%7CDAYTIMERANGE&dateTime.endDateTime=10.06.2024+00:00%7CCET%7CDAYTIMERANGE&area.values=CTY%7C10Y1001A1001A83F!BZN%7C10Y1001A1001A82H&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)) (the data provider for EU). And as far as I am aware, there is no real-time, hourly data on LNG usage in Europe available anywhere else :)

With that said, LNG only accounts for approximately 7% of the gas in Germany [according to this article](https://www.cleanenergywire.org/news/german-gas-use-decreases-while-imports-and-exports-drop-2023), so it might also be less crucial as time goes.

Since this is in-actionable for now, I'll close this issue again, but feel free to respond still :)
