### ISSUE TITLE
Wind layer is not working on Safari

### ISSUE THREAD

**Issue by madsnedergaard** [electricitymaps/electricitymaps-contrib#6833]
**Describe the bug**
The wind particles are not disappearing/fading out as they should, meaning that the map quickly gets flooded with colors.

**To Reproduce**
1. Open website in Safari (on MacOS Sonoma)
2. Enable wind layer
3. Wait a few seconds

**Expected behavior**
See how it works in Chrome

**Screenshots**
![Screenshot 2024-06-16 at 22 16 09](https://github.com/electricitymaps/electricitymaps-contrib/assets/3296643/408579e3-0675-4743-8ad3-c0046d9ce548)

**Desktop (if relevant):**
 - OS: MacOS
 - Browser Safari 
 - Version 17

**Comment by VIKTORVAV99** [comment]
Turns out it is working on the Safari Technical Preview!
<img width="1324" alt="image" src="https://github.com/electricitymaps/electricitymaps-contrib/assets/30777521/46e4b4eb-17cd-4452-9c9b-3121c25f6e67">

Which makes me think we should not fix it as it's not broken but rather just unsupported at the moment?

**Comment by madsnedergaard** [comment]
Yeeeah, might be the easiest solution at least 😓

**Comment by madsnedergaard** [comment]
Resolved! :)
