### ISSUE TITLE
FR-COR (Corsica): Production parser is down

### ISSUE THREAD

**Issue by FelixDQ** [electricitymaps/electricitymaps-contrib#7065]
## Description

It looks like the dataset we used for real-time production breakdowns is no longer available:
The [URL](https://opendata-corse.edf.fr/api/v2/catalog/datasets/production-delectricite-par-filiere-en-temps-reel/exports/json) now returns:
```
{'error_code': 'NotFoundResource', 'message': 'The requested dataset production-delectricite-par-filiere-en-temps-reel does not exist.'}
```

Does anyone know if the data was moved to a different URL or if there's a different source available?

**Comment by Gwemox** [comment]
Maybe this dataset "production-d-electricite-par-filiere-et-couts-de-production-au-pas-horaire"?

https://opendata-corse.edf.fr/api/v2/catalog/datasets/production-d-electricite-par-filiere-et-couts-de-production-au-pas-horaire/exports/json

**Comment by t-couery** [comment]
I updated the FR_COR parser and looked at the Corsican data. 
The dataset `production-delectricite-par-filiere-en-temps-reel` no longer exists. The dataset `production-d-electricite-par-filiere-et-couts-de-production-au-pas-horaire` has no data since end of 2022.

Finding no other solution, I didn't modify this part of the parser.

**Comment by t-couery** [comment]
Corsican data are available again with a new API / mapping
https://opendata-corse.edf.fr/api/explore/v2.1/catalog/datasets/production-delectricite-par-filiere-en-temps-reel/exports/json

**Comment by t-couery** [comment]
This issue can be closed now.
