### ISSUE TITLE
[Data Issue]: Electricity generation at La Réunion (RE) misrepresented

### ISSUE THREAD

**Issue by Charles-Fache** [electricitymaps/electricitymaps-contrib#7280]
### When did this happen?

2024-10-04 15-29

### What zones are affected?

RE

### What is the problem?

Disclaimer : this is the first time I dig a bit into how electricitymaps works, please tell me if I got something wrong.

Electricitymaps displays electricity generation for RE for hourly, daily and monthly ranges as using fossil fuel even though it now is [100% renewable](https://www.edf.fr/groupe-edf/espaces-dedies/journalistes/tous-les-communiques-de-presse/avec-la-conversion-de-la-centrale-de-port-est-a-la-biomasse-liquide-le-parc-de-production-dedf-a-la-reunion-atteint-100-denergies-renouvelables) thanks to using biomass (a lot of liquid biomass in particular) where fossil fuels were previously used. 

Data from the [source cited on electricity maps](https://opendata-reunion.edf.fr/) shows no fossil electricity generation (at least by browsing it as a human in a browser, I didn't test the API).

I took a look at the [FR_O parser](https://github.com/electricitymaps/electricitymaps-contrib/blob/master/parsers/FR_O.py) which I believe might be the culprit and it seems that the data is actually pulled from this other [open-data site by EDF](https://opendata.edf.fr) instead (except when no date-time is provided ?), for which I didn't take a look at what the API returns but I suspect this may be the cause.

Edit : I've only looked into RE but this mix-up between biomass and fossil fuels _might_ also happen for the rest of the regions covered by the FR_O parser

**Comment by t-couery** [comment]
I looked at what Charles-Fache said and there is indeed a problem on Reunion Island.
The problem comes from the Json attributes, which are not correct. The CSV version allows you to see the problem. It's linked to the change in the engine's fuel system in end og 2023 :

> The plant’s twelve engines previously running on oil, are now operating on liquid biomass made from rapeseed oil.

https://www.edf.fr/en/the-edf-group/dedicated-sections/journalists/all-press-releases/after-the-conversion-of-the-port-est-power-plant-to-liquid-biomass-edfs-power-generating-fleet-in-reunion-island-reaches-100-of-renewable-energy



Example for the same hour :

https://opendata-reunion.edf.fr/api/v2/catalog/datasets/prod-electricite-temps-reel/exports/json
`{"date": "2024-10-28T01:55:00+04:00", "eolien": 0.4198, "hydraulique": 10.834, "photovoltaique": 3.72, "charbon": -5.7618, "bioenergies": 2.8798, "diesel": 178.564, "stockage": -0.0512, "total": 254.284, "jour": "2024-10-28", "statut": "Estim\u00e9", "heure": null, "turbines_combustion": 63.68}`

https://opendata-reunion.edf.fr/api/v2/catalog/datasets/prod-electricite-temps-reel/exports/csv
`Date;Eolien (MW);Hydraulique (MW);Photovoltaïque (MW);Biomasse (MW);Bioénergies (MW);Bioliquide (MW);Solde stockage;Total (MW);jour;Statut;Heure;Turbines à combustion (MW)
2024-10-28T01:55:00+04:00;0.4198;10.834;3.72;-5.7618;2.8798;178.564;-0.0512;254.284;2024-10-28;Estimé;;63.68`

charbon (coal) is in fact Biomasse (**biomass**)
diesel (oil) is in fact Bioénergies (**biomass**)

This can be fixed by using the CSV version or by changing the mapping for RE in FR_O parser

The other GF, MQ, GP and FR-COR (Corse) are not impacted by the same issue (but needs to be reviewed)

**Comment by FelixDQ** [comment]
Thank you both for the investigation. If anyone has time, it would be great to update the parser. There are instructions for how to set up the local development in our wiki [here](https://github.com/electricitymaps/electricitymaps-contrib/wiki/Fixing-a-broken-parser)

**Comment by t-couery** [comment]
Hello,

I think I can help on that, I'm looking to update the [FR_O](https://github.com/electricitymaps/electricitymaps-contrib/blob/master/parsers/FR_O.py) parser.

**Comment by t-couery** [comment]
I hope I did the modifications correctly, this is my first parser modification on the project. Please let me know if there are any changes to be made.

**Comment by t-couery** [comment]
The Electricitymaps data are now consistent with Réunion's production, so this issue can be closed.

![{D662FB2F-D3BD-4CFD-8876-048C3713169D}](https://github.com/user-attachments/assets/e6201aef-c556-4f9e-a61c-94fe7869c205)
![{7AC997D2-3D26-49B9-8793-0AD9DDA6D995}](https://github.com/user-attachments/assets/f9255d80-a8dc-4bb7-a821-faf8eea0ba49)

**Comment by Charles-Fache** [comment]
Thanks to everyone who contributed, is there a way to make this change retroactive so that historical data isn't still showing fossil fuel use up until november 10th 2024 (last sunday)? 
![image](https://github.com/user-attachments/assets/90ebf520-a099-4978-af52-f5c893fed2ad)

**Comment by VIKTORVAV99** [comment]
> Thanks to everyone who contributed, is there a way to make this change retroactive so that historical data isn't still showing fossil fuel use up until november 10th 2024 (last sunday)? ![image](https://private-user-images.githubusercontent.com/103630659/386602093-90ebf520-a099-4978-af52-f5c893fed2ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NDMyNTMsIm5iZiI6MTczMTg0Mjk1MywicGF0aCI6Ii8xMDM2MzA2NTkvMzg2NjAyMDkzLTkwZWJmNTIwLWEwOTktNDk3OC1hZjUyLWY1Yzg5M2ZlZDJhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxMTI5MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzJkMzk5MTU3MDkzOTZiMmQyM2IzYjk0ZDBiNTNiYmY0NDc4YjQxMDA0MmE3NmZhOGU5NWE1YzM3YTZmYThkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.F8HehtFNo0EjAYfTMqCd5I2jYMgZu2YbxWkvXJDG7yI)

We will refetch as much data as we can and reprocess that but I have no idea of how much historical data we can get anymore. So I can’t give any guarantees.

**Comment by VIKTORVAV99** [comment]
Looked at how much data we can get and it's only the last few days on a rolling basis so we can't adjust the historical data here. At least not with out current parser.
